### ISSUE TITLE
API: get_params()

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#164]
As observed in #141 (but also in #110 and https://github.com/benanne/Lasagne/issues/136#issuecomment-75169847), it's not entirely clear what `Layer.get_params()` means and what it should mean.

The documentation of `get_params()` says: "Returns a list of all the Theano variables that parameterize the layer.", and further below it says "it should be overridden in a subclass that has trainable parameters".
In addition, we have `get_bias_params()`, which is documented as: "Returns a list of all the Theano variables that are bias parameters for the layer.", and a note further below says "This is useful when specifying regularization (it is often undesirable to regularize bias parameters)."

Now when we include the use case of Batch Normalization, we actually have three overlapping classes of variables:

1. variables involved in the forward pass (currently `get_params()` according to its docstring)
2. variables to be updated wrt. the loss function (currently `get_params()` according to its usage in Lasagne)
3. variables to be updated wrt. the loss function that are not to be included in weight regularization (currently `get_bias_params()`)

Before the first release of Lasagne we should re-think the `get_params` and `get_bias_params` API. It obviously does not exactly match what comes up in the use cases. Should we possibly replace this with a single `get_params()` method with optional keyword arguments to filter out certain things? Most Layer classes would not need to bother with the keywords or just react on the bias-related keyword, so it wouldn't increase the complexity of adding a new Layer class. Shall we think that through?

**Comment by benanne** [comment]
I agree, there is a distinction between the "parameters that should be learned" and the "parameters that should be serialized" that pops up sometimes. For most layers these are the same, but I guess this isn't always the case.

I like the idea of having a single method and controlling its behaviour with optional keyword arguments, which allows us to ignore this issue in 95% of use cases. It also allows easy extension later by defining new keyword arguments, in case we discover there are other kinds of parameter groupings as well.

The alternative seems to be to add an extra method to distinguish the two current `get_params()` use cases, but that makes the interface bigger so I don't like the idea much. It could also set a bad precedent.

So let's think this through indeed!

**Comment by craffel** [comment]
First (I think everyone will agree with this), it seems like we should require all layers to have a `get_params` which can return all of their parameters no matter what (weight matrices, bias vectors, recurrent layer initializations, nonlinearity parameters, etc.)  Beyond that, one option I like is to have layers optionally have a variety of other convenience methods depending on what their parameters are, e.g. `get_weight_params`, `get_bias_params`, `get_init_params`, etc.  However, this is functionally pretty similar to have something like `get_params` take keyword args to include/exclude certain types of params, e.g. `get_params(include_weights=True, include_biases=False)` (as proposed by @f0k).  A potential use case which is making me like the keyword argument style is that (assuming that we make it so that get_params can ignore unused kwargs), we could then make `get_all_params` pass keyword args onto its `get_params` calls, the hope being that you could call e.g. `get_all_params(include_biases=False)` to get all weight params for all layers.  The obvious problem with that (assuming all kwargs would default to `True`) is that you'd have to make sure you added `include_*=False` for all of the parameter types you don't want to include, which is potentially verbose and also error-prone (it'd be easy to forget/not know about a param type when you're trying to get one specific type).  On the other hand, with the separate function approach ( `get_weight_params`, `get_bias_params`, ...), you couldn't really do this at all because you'd potentially be trying to call member functions which don't exist for some layers.  Does that all make sense?  Any ideas?

**Comment by benanne** [comment]
There's no reason why they keyword arguments should be of the form `include_...`. It might make more sense to have the keyword arguments be `bias=True` or `trainable=True` or something like that, and then only this subset of parameters is returned (short and easy to remember).

And I agree, `get_all_params()` is another good reason to go with the keyword argument approach.

**Comment by craffel** [comment]
> There's no reason why the keyword arguments should be of the form include_.... It might make more sense to have the keyword arguments be bias=True or trainable=True or something like that, and then only this subset of parameters is returned (short and easy to remember).

Ah, so you're saying that one of the keyword args being set to true denotes "only return params of this type", not "include parameters of this type"?  In that case, we'd have to define the behavior (an error?) when more than one kwarg was set to `True`.  If both `bias=True` and `weights=True` being set would denote "return both bias and weights", then this is equivalent to the "include" case, as far as I can tell.

**Comment by f0k** [comment]
Implementation-wise it would be good to only have keywords that restrict the set of returned variables, no keywords that extend it. Not giving any keywords would equal to "return all variables involved in the forward pass" then (note that I explicitly say "variables", not "parameters" -- constant parameters that are set in the constructor, such as the dropout rate for the `DropoutLayer`, should not be returned here). Implementations oblivious to keywords would look like:
```python
def get_params(self, **kwargs):
    return [self.X, self.Y, self.Z]
```
Other implementations would look like:
```python
def get_params(self, **kwargs):
    result = [self.W]
    if not kwargs.get('no_biases'):
        result += [self.b]
    if not kwargs.get('trainable_only'):
        result += [self.asdf]
    return result
```
We'd just need to decide on the terms to use. I don't really like `no_biases` because what we really wanted was to exclude parameters that are not to be regularized, such as the initial state vectors in #110. I'm not terribly sure about `trainable_only` either.

In any case, we should drop `get_bias_params()` when we revamped `get_params()`. That's an interface change we need to do before the first release. @benanne, can you please set the milestone? (I'm not allowed to.)

**Comment by benanne** [comment]
Agreed, keywords should filter the list.

Maybe instead of `no_biases` we could have a keyword argument `regularized`, because what we usually want to 'select' is the parameters that are to be included for regularization, not the biases. I'd also suggest `trainable` instead of `trainable_only`. The fact that specifying a keyword filters the list should be implied.

**Comment by ebenolson** [comment]
I think you should consider letting layers store coefficients for the individual learning rates, regularization strength, etc. of their parameters. Then things that shouldn't be trained/regularized are just a special case with a coefficient of `0`. 

In whatever function was using the parameters, you would give an argument like `"train"` or `"regularize"` to `get_params` to select the proper coefficients.

This would also make it simple to do things like load weights from a pretrained model and then "freeze" certain layers while fine-tuning.

**Comment by benanne** [comment]
I don't like the idea of storing hyperparameters in layer classes - even if they are layer-specific. I don't see how we could do this without complicating other, more common use cases a lot.

**Comment by f0k** [comment]
> Maybe instead of `no_biases` we could have a keyword argument `regularized`, because what we usually want to 'select' is the parameters that are to be included for regularization, not the biases. I'd also suggest `trainable` instead of `trainable_only`

Okay. To match `trainable`, the first one should actually be called `regularizable` (because the parameters are not regularized until you actually regularize them, similar to how parameters are not trained until you train them).

I'd prefer `trainable_only` instead of `trainable` because it makes clear what happens when you do `trainable_only=False` (in contrast, `trainable=False` sounds as if you would want to exclude trainable parameters from being returned; and we cannot implement that because it would require all `get_params()` implementations to know about all keywords introduced in future).

**Comment by benanne** [comment]
You wouldn't ever call the function with `trainable=False` though, since that is the default anyway. So I think `trainable` and `regularized` would be fine.

`regularizable` sounds a bit cumbersome to me (it's not a very common word), but I guess it's a good match. Maybe there's another alternative we can get behind?

Anyway, I won't make a fuss if we go with `trainable_only`, I just think the suffix is unnecessary.

**Comment by f0k** [comment]
Thinking about it, I'd even be slightly confused by `get_params(trainable=True)`, because that sounds as if `get_params()` would not return trainable parameters by default (as it implies that the default is `trainable=False`). So I'm strongly in favor of `trainable_only`. I think the extra verbosity is justified.

> `regularizable` sounds a bit cumbersome to me (it's not a very common word), but I guess it's a good match. Maybe there's another alternative we can get behind?

That would be good. I was thinking of `regular_only`, but that's not really good.

Another question to ponder: Do we want to allow people to only retrieve the initialization vectors of RNNs? That wouldn't work with the proposed scheme, because all layers would have to know to not return anything for `get_params(init_only=True)`. That's something we actually wanted to avoid -- we wanted implementations to be oblivious to keywords they don't know. Another way would be for layer implementations to *tag* their parameters, and have `get_params(only=('trainable', 'regularizable'))` do the work in a general implementation in the base class. That would also easily allow something like `get_params(only='trainable', exclude='regularizable')`.

**Comment by benanne** [comment]
Yeah, maybe a more flexible approach like that is in order. The relevant tags can just be passed to `create_param` as keyword arguments or something. We should have sensible defaults for them as well, so `trainable` and `regularizable` should probably default to `True` or something.

Anyway, this needs to be thought through first because it does sound like it would add a bunch of complexity. Ideally this should be completely invisible to users who don't need this.

**Comment by f0k** [comment]
> The relevant tags can just be passed to `create_param` as keyword arguments or something.

Oh, is it required to instantiate parameters via `create_param`? I think tagging would work by adding parameters to some dictionary on construction time, or by calling a base class registration function, or by having the base class `get_params()` call an overridable `get_params_for()`-like method (an apt name would be `get_all_params()` ;) ).

> We should have sensible defaults for them as well, so `trainable` and `regularizable` should probably default to `True` or something.

Ah yes, there's always a catch.
* If we want to limit `get_params()` to `xyz_only=True` keywords and be able to expand the set of tags at any time, this implies that all parameters have all tags unless a Layer explicitly tells they don't (via an `if` clause checking for the keyword). This means we cannot add something like `init_only` later on.
* If we want to limit `get_params()` to `exclude_xyz=True` keywords and be able to expand the set of tags at any time, this implies that all parameters have no tags unless a Layer explicitly tells they do (via an `if` clause checking for the keyword). This means almost all layers will have to define their parameters to be trainable and regularizable.
* If we want `get_params()` to support both `only=(...)` and `exclude=(...)` keywords and be able to expand the set of tags at any time, we can choose what to do, but it probably means all parameters have no tags unless a Layer explicitly tells they do (via some dictionary entry or base class registration).

> Anyway, this needs to be thought through first because it does sound like it would add a bunch of complexity. Ideally this should be completely invisible to users who don't need this.

Agreed, it adds some complexity, as users (= people writing `Layer` implementations) would have to tag all parameters appropriately, and read more code to fully understand the tagging system. The current interface is much simpler, and a keyword-based `get_params(trainable_only=..., **kwargs)` would be about as simple as the current interface.

**Comment by benanne** [comment]
`create_param` currently isn't a requirement, but it's how it's done in all existing `Layer` implementations afaik, so we might as well make it a requirement. This would then also function as the 'base class registration function'.

> * If we want to limit `get_params()` to `xyz_only=True` keywords and be able to expand the set of tags at any time, this implies that all parameters have all tags unless a Layer explicitly tells they don't (via an `if` clause checking for the keyword). This means we cannot add something like `init_only` later on.

I don't understand why this is a problem? why couldn't we add more keywords later with this approach? I'm probably missing something.

> * If we want `get_params()` to support both `only=(...)` and `exclude=(...)` keywords and be able to expand the set of tags at any time, we can choose what to do, but it probably means all parameters have no tags unless a Layer explicitly tells they do (via some dictionary entry or base class registration).

I think all parameters should at least be marked `trainable` by default, because that accounts for 95% of use cases. Marking them `regularizable` by default is probably also a good idea because it's more natural to "exclude the biases from regularization".

> Agreed, it adds some complexity, as users (= people writing `Layer` implementations) would have to tag all parameters appropriately, and read more code to fully understand the tagging system. The current interface is much simpler, and a keyword-based `get_params(trainable_only=..., **kwargs)` would be about as simple as the current interface.

It would be pretty straightforward to understand from examples though, and if `trainable` is True by default, most people won't even have to think about it. In `DenseLayer` we'd have:

```
self.W = self.create_param(W, (num_inputs, num_units), name="W")
self.b = (self.create_param(b, (num_units,), name="b", regularizable=False)
          if b is not None else None)
```

`trainable=True` is implied. Maybe also `serializable=True`, although there probably aren't any use cases for non-serializable parameters. I can't think of any, at any rate, so we probably wouldn't need a tag for this.

We'd have to modify `create_params` to 'register' the parameters, which would be easy to do and actually quite intuitive. The explicit implementations of `get_params()` and `get_bias_params()` would be removed, and `get_params()` with keyword args would just be implemented in the base class.

It's only when you want to do fancy stuff (like batch normalization) that you would have to know how this works.

Where does this break down? I have a feeling you're seeing some flaws in this but I don't really understand your explanation of them.

**Comment by f0k** [comment]
>> If we want to limit `get_params()` to `xyz_only=True` keywords and be able to expand the set of tags at any time, this implies that all parameters have all tags unless a Layer explicitly tells they don't (via an `if` clause checking for the keyword). This means we cannot add something like `init_only` later on.

> I don't understand why this is a problem? why couldn't we add more keywords later with this approach? I'm probably missing something.

That's the case [I've mentioned above](https://github.com/benanne/Lasagne/issues/164#issuecomment-82892201): We can of course add a keyword `init_only`. However, we cannot have it only gather all the initial hidden state vectors of recurrent layers, because as I said, this setup would imply " that all parameters have all tags unless a Layer explicitly tells they don't". So while we could add keywords to exclude things that nobody had thought of before, we couldn't add keywords to limit the scope to things that nobody had thought of before. (All under the assumption that we cannot modify all existing Lasagne Layers in the world whenever introducing a keyword, otherwise it would be easy.)

My second option would be about as easy as the current `get_params()` implementation, and it would not have the problem above, but it would make things harder for users of layers (as opposed to developers of layers). We'd have to define keywords such as `exclude_biases` and `exclude_untrainable` then, which would be a little awkward, and instead of `init_only` we could only define something like `exclude_not_init`, which would be more than a little awkward.

So I think we can't get around a tagging system.

> Where does this break down? I have a feeling you're seeing some flaws in this but I don't really understand your explanation of them.

It's probably just that the previous implementation looked easier, and that not requiring `create_param` seems to make things more flexible. `create_param` currently requires the parameter shape to be known, while `register_param` would just require a symbolic variable. If we require `create_param` now, it's possible that we will need a separate method at some point for a situation where you only know the parameters, but not their shape.

> `self.create_param(b, (num_units,), name="b", regularizable=False)`
While I like the syntax, I'm pretty sure we shouldn't use keyword arguments for the tags because then we can never extend `create_params` with more parameters. If we want to use keyword arguments, we need a separate registration function. I see three solutions:

1. We use a syntax with a dictionary or list, such as `self.create_param(b, (num_units,), name="b", tags={'regularizable': False})`
2. We add a function `register_param(param, trainable=True, regularizable=True, **kwargs)` that needs to be called on every parameter to be registered, whether they come from `create_param` or not. For convenience, it could return `param`.
3. We add a function `tag_param(param, **kwargs)` that allows to a) extend/change the tags that are normally assigned to a parameter by `create_param`, and b) register parameters that were not created by `create_param` at all

With the second option, your example would become:
```python
self.W = self.register_param(self.create_param(W, (num_inputs, num_units), name="W"))
self.b = (self.register_param(self.create_param(b, (num_units,), name="b"), regularizable=False)
          if b is not None else None)
```
(Although I think separate `register_param` statements would be nicer.)

With the third option, your example would become:
```python
self.W = self.create_param(W, (num_inputs, num_units), name="W")
if b is not None:
    b = self.create_param(b, (num_units,), name="b")
    self.tag_param(b, regularizable=False)
self.b = b
```

**Comment by benanne** [comment]
I really feel like there is some kind of misunderstanding here. I don't see why things have to be quite so complicated. I don't think parameters should have all tags by default, or no tags by default. I think this should be tag-dependent. For `trainable` it makes sense to have it on by default, becuse 95% of use cases will involve trainable parameters. For other tags, it might not. We can just pick the best option on a per-tag basis. I really don't see any reason why all tags should be either on by default or off by default.

This is also why I don't like the idea of having to explicitly specify for each parameter that it is trainable. This is the most common use case, so it should be the default.

> not requiring create_param seems to make things more flexible.

Does it? As I said, all current layer implementations use it. What would be an example use case for not using it? Also, what's an example use case where we have a parameter whose shape is not known in advance? I thought this was a fairly safe assumption.

If the ability to have parameters without predefined shapes is really needed, maybe we can figure out a way to relax the requirement in `create_param`. Having a separate method `register_param` just seems needlessly complex. What would be an example use case where you want to create a parameter but not register it?

> While I like the syntax, I'm pretty sure we shouldn't use keyword arguments for the tags because then we can never extend create_params with more parameters.

Why not? Because of potential conflicts between tags and actual keyword arguments? What is the likelihood of that happening? Just being pragmatic here :) `tags={'regularizable': False}` seems like a lot of cruft.

**Comment by f0k** [comment]
> I really feel like there is some kind of misunderstanding here. I don't see why things have to be quite so complicated. I don't think parameters should have all tags by default, or no tags by default.

That was referring to the [first two implementation options](https://github.com/benanne/Lasagne/issues/164#issuecomment-82933393) that don't use a "tagging system", but just extend the current per-layer `get_params()` implementation with a set of `if not trainable_only: ...` clauses, [as previously illustrated](https://github.com/benanne/Lasagne/issues/164#issuecomment-78455547). Depending on which of those two options we chose, we would either implicitly assume parameters have all tags set by default, or no tags set by default. (Where "default" means a `get_params()` implementation that doesn't have an `if` clause for a keyword.)

> This is also why I don't like the idea of having to explicitly specify for each parameter that it is trainable. This is the most common use case, so it should be the default.

If we go for a tagging system (and I think we have to), then we're of course free to make whatever default assumptions we want. And then I agree that `trainable` and `regularizable` would be very reasonable defaults.

> What would be an example use case for not using it? Also, what's an example use case where we have a parameter whose shape is not known in advance? I thought this was a fairly safe assumption.

I don't know, it's what my crystal ball says ([it also said](https://github.com/benanne/Lasagne/issues/4#issuecomment-55319942) that we shouldn't have `get_params` and `get_bias_params` five months ago, so I've come to trust it).
A possible example would be creating a Layer wrapping/proxying an existing Layer, with existing parameters plus some of its own. It would be awkward to use `get_value()` on all existing parameters just in order to pass a shape to `create_param` which will then be ignored.
And actually I think we even encounter this in `RecurrentLayer`, when a stack of layers is passed as the input-to-hidden or hidden-to-hidden transform. Currently, `RecurrentLayer.get_params()` just calls `get_params()` on all these wrapped layers. This would still work, but if it wanted to change/extend the tags, `RecurrentLayer` would need to properly register the params itself instead of overwriting `RecurrentLayer.get_params()`.
Are you convinced yet? :)

> What would be an example use case where you want to create a parameter but not register it?

I cannot imagine one. I can only imagine that you might want to register the parameters in a different order than you created them, but that's not crucial at all. I'm not against having `create_param` register a parameter implicitly, I'm just against making `create_param` the only way to do so.

> Why not? Because of potential conflicts between tags and actual keyword arguments?

Yes, people might invent arbitrary tags that we don't know about, and we could break their code by adding more keyword arguments to `create_param`.

> `tags={'regularizable': False}` seems like a lot of cruft.

Agreed. That's why I'd prefer a `register_param` or `tag_param` or `tag_params` method. And [as in my example](https://github.com/benanne/Lasagne/issues/164#issuecomment-82966078), that method could be called automatically by `create_param` so it only needs to be called a) if the default tags are not appropriate for a parameter or b) if a parameter is not created via `create_param`.

**Comment by benanne** [comment]
> That was referring to the first two implementation options that don't use a "tagging system"

Okay, that explains my confusion, I thought we were talking about tagging. Sorry!

> Are you convinced yet? :)

No, I will need some time to study this before I understand these use cases, I think. I'm not familiar with any of the recurrent stuff and the 'wrapping a layer' use case seems a bit contrived, to be honest. I don't want us to fall into the trap of trying to support every possible use case ever. YAGNI is a good principle to adhere to.

> Yes, people might invent arbitrary tags that we don't know about, and we could break their code by adding more keyword arguments to create_param.

I think that's something we could live with, to be honest. The probability of this happening is vanishingly small. It's a bit inconvenient if it does happen, but typing `tags={'regularizable': False}` instead of `regularizable=False` all the time affects many more people and I think it will add up to a lot more inconvenience in the long run.

> Agreed. That's why I'd prefer a `register_param` or `tag_param` or `tag_params` method. And [as in my example](https://github.com/benanne/Lasagne/issues/164#issuecomment-82966078), that method could be called automatically by `create_param` so it only needs to be called a) if the default tags are not appropriate for a parameter or b) if a parameter is not created via `create_param`.

I'm still uncomfortable with having a separate method for this. Tags are intrinsic to parameters, they don't change after they are created. It just makes a lot of sense to set them at creation time. It also allows us to avoid exposing the concept of 'tags' to people who don't need to know about it, reducing cognitive overhead. It's more natural to think "I don't want this parameter to be regularized, so I'll set `regularizable=False` when creating it" than "I need to set the `regularizable` tag of this parameter to `False`". The fact that there is an underlying 'tagging' system that enables this is irrelevant for most people and it would be nice if we didn't have to bother them with it.

I also think the 'parameters not created with `create_param`' use case is too uncommon to worry about, and definitely not worth the extra verbosity. But as I said I've yet to grok those use cases you listed.

**Comment by f0k** [comment]
By the way, it's good to have these "extensible and clean" vs "simple and pragmatic" discussions every now and then :+1: Doesn't anybody else want to chime in?

Another solution I would subscribe to would be to rename `create_param` to `add_param`, make the `shape` optional, and provide a `tag_params(*params, **tags)` method to mass-change the tags of one or more registered parameters. `add_param(spec, shape=None, name=None, **tags)` would be *okay* as well, although we might break code with this.

**Comment by ebenolson** [comment]
Why have `create_param` be part of the `Layer` class at all? It seems like something that could be useful in other places.

Why not create a `Param` class that encapsulates the Theano variables? Then instead of `create_param` and `tag_params`, you can do something like

    W = Param(shape=shape, name='w')
    W.tags['trainable'] = True # tags is a dict attribute of the Param class

If you want maximal compatibility with existing code, you can make the `get_all_params` function unwrap the `Param` and return the bare Theano variables.

**Comment by benanne** [comment]
> Why have `create_param` be part of the `Layer` class at all? It seems like something that could be useful in other places.

What would be a use case of `create_param` outside of the `Layer` class? Right now `create_param` has to be a `Layer` method because parameters are named based on the name of the layer they are part of, but I guess that is a minor concern.

> Why not create a `Param` class that encapsulates the Theano variables?

I don't think we should wrap Theano objects if we can avoid it (see 'small interfaces' and 'transparency' in the list of design goals).

**Comment by benanne** [comment]
> `add_param(spec, shape=None, name=None, **tags)` would be *okay* as well, although we might break code with this.

That's pretty much what I had in mind, minus the renaming to `add_param`, but I could definitely live with that.

**Comment by f0k** [comment]
Ah, communication overlap.

> No, I will need some time to study this before I understand these use cases, I think. I'm not familiar with any of the recurrent stuff and the 'wrapping a layer' use case seems a bit contrived, to be honest.

All right, here's the `RecurrentLayer` code you need to see: https://github.com/craffel/nntools/blob/master/lasagne/layers/recurrent.py#L66-100
Note how the Layer internally hosts other Layer instances that are not exposed to the outside, but participate in the `get_output_for()` call, such that they also need to be included in the `get_params()` methods to be learned. This is a case of 'wrapping a layer'. The `RecurrentLayer` doesn't know anything about the Layer instances it hosts, especially it doesn't know about their parameter shapes.
When `get_params()` gets replaced by a "tagging system" implemented in the base class, the `RecurrentLayer` either needs a way to register those parameters as its own, or it needs to overwrite `get_params()`. If it overwrites `get_params()`, it will have to call the super class `get_params()` to invoke the tagging system for its own parameters (here: `self.hid_init`), which will be quite messy.
Hmm, thinking again, there is actually no way around overwriting `get_params()`, because it doesn't know the tags of the parameters of the Layer instances it hosts, so it cannot register them itself.

Well then... I guess the use case I had in mind always has to be done by overwriting `get_params()`. This means I'm fine if `create_param` requires the `shape` argument to be given. I'm still strongly for renaming it to `add_param` to reflect the changed semantics. We need to touch all `Layer` classes anyway because `get_params()` and `get_bias_params()` will be dropped, so we can just rename it on the way.

**Comment by f0k** [comment]
> Tags are intrinsic to parameters, they don't change after they are created.

Maybe I (as a user of existing layers, not as a developer of new layers) want to tag particular parameters with custom tags while creating a network architecture, such that I can easily retrieve groups of parameters afterwards via `get_all_params()`. Is this a use case worth supporting, or would that invite people to write spaghetti code? (Note that right now, all Layer methods are public, so anybody could call `add_param` on any instance. We could have a `tag_params` method as well.)

**Comment by benanne** [comment]
I don't know if that's worth supporting, what would be a use case for that? It seems to me that it's only slightly more complicated to manually construct a Python list of those parameter variables you want to retrieve, than to call `tag_params` on all of them.

**Comment by f0k** [comment]
> I don't know if that's worth supporting, what would be a use case for that?

In my codebase, the network is created fully independently of the training algorithm. I could tag some parameters to be frozen, or remove the `regularizable` tag from some parameters, and the training algorithm could use a few `get_all_params()` calls to build the update expressions, apply norm constraints and the like. Otherwise I'd always need to pass Python lists along with the network to apply custom tags to parameters, or subclass the Layer classes.

But we don't need to discuss that now, because a) this could be added at any time later and b) it may not need a separate function anyway, depending on how the tagging system is implemented (if it's a `Layer.parameters` dictionary, I could just modify the dictionary, there shouldn't be a need to hide it from the user).

**Comment by f0k** [comment]
Regarding the implementation, the easiest might be a list (to have a definite order) plus a dictionary of sets:
```python
def add_param(self, spec, shape=None, name=None, **tags):
    param = what_the_former_create_param_did(spec, shape, name)
    self.params.append(param)
    tags['trainable'] = tags.get('trainable', True)
    tags['regularizable'] = tags.get('regularizable', True)
    for tag, val in tags.items():
        if val:
            self.param_tags[tag].add(param)

def get_params(self, only=None, exclude=None):
    only = set.intersection(self.param_tags[tag] for tag in only) if only else set(self.params)
    exclude = set.union(self.param_tags[tag] for tag in exclude) if exclude else set()
    result = only - exclude
    return [param for param in self.params if param in result]
```

This would require a call of the form `get_params(only=['trainable'], exclude=['regularizable'])`. We could also settle for a `get_params(trainable=True, regularizable=False)` form:
```python
def get_params(self, **tags):
    result = set(self.params)
    for tag, val in tags.items():
        if val:
            result &= self.param_tags[tag]
        else:
            result -= self.param_tags[tag]
    return [param for param in self.params if param in result]
```

**Comment by f0k** [comment]
Another solution would be an OrderedDict of sets that maps parameters to tags:
```python
def add_param(self, spec, shape=None, name=None, **tags):
    param = what_the_former_create_param_did(spec, shape, name)
    tags['trainable'] = tags.get('trainable', True)
    tags['regularizable'] = tags.get('regularizable', True)
    self.params[param] = set(tag for tag, value in tags.items() if value)

def get_params(self, **tags):
    result = self.params.keys()
    only = set(tag for tag, value in tags.items() if value)
    if only:
        # retain all parameters that have all of the tags in `only`
        result = [param for param in result if not (only - self.params[param])]
    exclude = set(tag for tag, value in tags.items() if not value)
    if exclude:
        # retain all parameters that have none of the tags in `exclude`
        result = [param for param in result if not (self.params[param] & exclude)]
    return result
```

Compared to my previous suggestion, this would make it easier to manipulate registered tags or pass them around (including their tags), and to remove parameters. It would require an OrderedDict, though, and `get_params()` is a little more verbose.
Note that if we don't want to fully encapsulate the tagging system with `tag_params()`, `remove_param()` etc. and hide the internal variables, it's crucial which implementation we choose now. We cannot change it later if we expose `self.params` to avoid a bunch of tag and parameter registration/removal functions. (Assuming that we want to allow changing tags and parameters outside of the constructor, which I'd advocate because I don't see a reason against it.)

**Comment by ebenolson** [comment]
Are you guys familiar with the blocks project? Their tagging/annotation system seems interesting: https://github.com/bartvm/blocks/blob/309adea53a9d3a1af573c75168b751299935eb24/docs/cg.rst

**Comment by f0k** [comment]
> It would require an OrderedDict, though, [...]

I see that in #23 we decided to require Python 2.7+, so this wouldn't be a problem. Shall I go ahead and implement my latest suggestion (make `Layer.parameters` an `OrderedDict` that maps each parameter to a set of strings denoting its tags)?

> Are you guys familiar with the blocks project?

No, not really, but it's nice to see that there are a lot of parallels to design decisions in Lasagne (weight initializers, tags for parameters, topological order of graph traversal results).

**Comment by ebenolson** [comment]
What is the advantage of the OrderedDict approach versus storing tags in a list added to the Theano variable, as in blocks?

**Comment by f0k** [comment]
> What is the advantage of the OrderedDict approach versus storing tags in a list added to the Theano variable, as in blocks?

Didn't see their implementation. So to get everybody in, what they do is adding a `role` attribute to the (already-existing) `tag` attribute of Theano variables, which then holds a list of `blocks.roles.VariableRole` instances.

To answer your question: (a) We don't want to tag all Theano variables that could participate in a graph, we just want to tag whatever a Layer declares as its parameters. It seems cleaner to me to implement this in a way that allows exactly that and nothing more. (b) If a parameter is used by multiple layers, the approach in `blocks` would have them overwrite the tags. If it doesn't overwrite the tags, but combines them, it could fail in other situations (e.g., re-using a parameter from one network to instantiate a new one). Managing the tags externally circumvents this.

What would be the advantage of adding the tags directly to the Theano variable? The only one I see is that the tags are always part of the parameters you get out of `get_all_params()` and the like, but we could have it optionally return an OrderedDict as well. (Another advantage is that you can still see the tags when traversing the computational graph, but that doesn't really count, as our traversal routines work on the graph of `lasagne.layers.Layer` instances rather than on Theano expressions, contrary to `brick`.)

**Comment by benanne** [comment]
I read on the mailing list that you are waiting for input on this - I didn't realise that!

I think your most recent proposal is fine and addresses all my concerns with the previous iterations. I think w should be able to easily set tags at creation time as keyword arguments (using `add_param`), and use the same keyword arguments as filters for `get_params`. It looks like the latest iteration enables both, so let's go for it :)

**Comment by benanne** [comment]
As mentioned by @f0k in https://github.com/Lasagne/Lasagne/pull/221#issuecomment-96364201, we should refactor the code so the creation of the variable based on the specified initializer (either a function, numpy array or shared variable) is in a utility function. `add_param` should be implemented on top of that.

Just putting this here so we don't forget about it.

**Comment by benanne** [comment]
Would it be okay if I took a stab at this (using your latest suggestion as a basis)?

**Comment by f0k** [comment]
Sure. I probably won't be able to work on #182 before the ISMIR deadline, though. You can also send me PRs for #182 if you want to help! I rebased it in the meantime.

**Comment by benanne** [comment]
This is done :) Yay!
