### ISSUE TITLE
do we need a Model class?

### ISSUE THREAD

**Issue by benanne** [Lasagne/Lasagne#2]
The current setup follows the old layers.py code (see https://github.com/benanne/kaggle-galaxies/blob/master/layers.py ), in the sense that there is no overarching `Model` class that aggregates the layers and takes care of communication between them. Instead, this is taken care of by whatever the topmost layer in your graph happens to be.

This design works because of Theano: a lot of things can be implemented by recursion, going from the topmost (output) layer to the lower layers. If we had to implement backprop this would be an issue, because then lower layers need references to higher layers. But luckily Theano takes care of that.

Nevertheless there may still be benefits attached to having an overarching `Model` class, so here's an issue about it so we can discuss the pros and cons.

At the moment I would prefer not to add it. I can't really think of good use cases for `Model` that can't be handled adequately by the current setup with only `Layer` (but of course that doesn't necessarily mean there aren't any). And since we're aiming for small interfaces, fewer classes is better.

**Comment by f0k** [comment]
Sparked by #104, in which we more or less agreed to pull out all graph traversal routines of `Layer`, I've rethought pulling out the necessary information (namely, `self.input_layer` and `self.input_layers`) as well. The graph traversal routines and the graph connections could be naturally kept together in a model class `lasagne.network.Network` (or `lasagne.model.Lasagne`). Basically, a connection `somelayer.input_layer = otherlayer` would become a dictionary entry `model.connections[somelayer] = otherlayer`.

While it's quite clear how a model class would implement `get_output()`, `get_all_params()` and the like, it's less clear how it would implement `add_layer()`. The problem is that a layer needs to know its input shape(s) at construction time, and the model needs to know a layer's input layer(s) at adding time. Right now (without a model class), we have:
```python
layer = InputLayer(someshape, somevar)
layer = DenseLayer(layer, num_units=128)
layer = DenseLayer(dropout(layer), num_units=1)
```
And then, `layer` is our handle to a simple MLP which takes `somevar` as its input. With a model class, we could have:
```python
network = lasagne.network.Network()
layer1 = InputLayer(someshape, somevar)
network.add_layer(layer1)
layer2 = DenseLayer(network.get_output_shape(layer1), num_units=128)
network.add_layer(layer2, input=layer1)
layer3 = dropout(network.get_output_shape(layer2))
network.add_layer(layer3, input=layer2)
layer4 = DenseLayer(network.get_output_shape(layer3), num_units=1)
network.add_layer(layer4, input=layer3)
```
`network.get_output_shape(layer1)` might be replaced by a `layer1.output_shape` property, but still it's cumbersome that we need to keep a reference to the previous layer once to get the shape and once to define the connection. We could make `input=` default to the last added layer to avoid that, but this would only help for simple stack-of-layer networks.
An alternative would be:
```python
network = lasagne.network.Network(someshape)
layer = network.add_layer(None, InputLayer, somevar)
layer = network.add_layer(layer, DenseLayer, num_units=128)
layer = network.add_layer(layer, dropout)
layer = network.add_layer(layer, DenseLayer, num_units=1)
```
This would defer constructing the layer to the network, which could then use the correct shape for the constructor call, but then we couldn't easily add self-instantiated layers, and we couldn't easily default to adding new layers to the most recently added layer (because we would need a keyword argument for that and couldn't distinguish it from arguments meant for the constructor call).

Another disadvantage of pulling out the connectivity information would be that we couldn't just write `dropout(layer)` or `concat([layer1, layer2])` any more, but would have to explicitly add a `DropoutLayer` or a `ConcatLayer` to our `Lasagne`/`Network`/whatever instance.

So unless someone comes up with a better solution for `add_layer`, for practical reasons I think we still shouldn't add a Model class to Lasagne (although the software engineer in me thought that would be so much cleaner).

**Comment by benanne** [comment]
Interesting analysis. I hadn't thought of a lot of those things. I'm still not opposed to having a model class that could optionally be used, but I guess it comes with a lot of limitations then. It might be better for consistency to stick with our current approach of having the output layer(s) represent the network.(and also because I guess "there should be only one way to do it").

**Comment by craffel** [comment]
Yeah, based on your discussion I think we can cover everything using the current paradigm and using functions like the proposed `get_output` - i.e., we can allow for arbitrarily structured (the AS in lasagne) networks with pretty intuitive syntax.  It is not necessarily the most convenient paradigm for certain things (like simple MLPs), but I think it's OK to let that be handled by other libraries like `nolearn`.
