### ISSUE TITLE
Acyclic graph networks

### ISSUE THREAD

**Issue by fchollet** [Lasagne/Lasagne#239]
I'm currently looking for interesting interfaces for handling the problem of acyclic graph networks. I thought I would check out Lasagne. 

Reading the docs, I see that Lasagne has a few 'merge' layers. 

- I was wondering if Lasagne also had reciprocal 'fork' layers? If not, is it something you plan on doing? 
- Why not a single Merge layer, with a 'mode' keyword argument to determine how the merge is handled?
- Is there any example of a fairly complex Lasagne model that I could take a look at?

**Comment by benanne** [comment]
* The need for 'fork' hasn't really come up, it seems like an uncommon operation. If anyone needs it I'm sure we can implement it, but it might make more sense to create a layer that selects a subset of features (i.e. just an indexing operation) and then use multiple of those.

A more common use case is to use the output of a layer as input to multiple other layers. Lasagne doesn't need a special class for that because it allows you to describe the graph directly. We are dealing with some issues surrounding that use case though (see #104, currently being addressed in #182).

* To me it makes more sense to have different classes for different functionality. I don't see the advantage of merging them and having to add a keyword argument to decide which of the code paths to use. They are not really interchangeable anyway (if I understand correctly you're talking about `ConcatLayer` and `ElemwiseSumLayer`)

* The examples in this repo are pretty limited for now. My team's solution for the National Data Science Bowl on Kaggle contains a couple somewhat more complex models: https://github.com/benanne/kaggle-ndsb/tree/master/configurations

This one uses the `ConcatLayer` for example: https://github.com/benanne/kaggle-ndsb/blob/master/configurations/cr4_ds.py#L142
as does this one: https://github.com/benanne/kaggle-ndsb/blob/master/configurations/cp8.py

**Comment by fchollet** [comment]
Cool, thanks for the links!

> To me it makes more sense to have different classes for different functionality. I don't see the advantage of merging them and having to add a keyword argument to decide which of the code paths to use. They are not really interchangeable anyway (if I understand correctly you're talking about ConcatLayer and ElemwiseSumLayer)

There is 0 technical advantage to doing it, but it makes the API simpler (i.e. usage requires less cognitive load) by hierarchically structuring information. A similar result would be achieved by grouping all merge layers in a 'layers.merge' module and giving the classes in the module minimal names (concat, sum, max, min). As you point out, they are not interchangeable, so the latter would probably be preferable. 

Is there any difference between `layers.ConcatLayer` and `layers.concat`, or are they wrappers for the same thing?

**Comment by benanne** [comment]
They are technically already in `lasagne.layers.merge`, but all layers are made available in the top-level `lasagne.layers` module precisely so people don't have to remember which submodule each layer is in (and also to save some typing).

`concat` is an alias for `ConcatLayer`. Several such aliases are provided for layers which are not typically considered "neural network layers" in literature. One of our guiding principles is to make our layers match this notion of a neural network layer as closely as possible. So there is also `dropout` for `DropoutLayer`, `flatten` for `FlattenLayer`, etc.

**Comment by fchollet** [comment]
Ok, thanks for the clarification!
