### ISSUE TITLE
Null loss values in examples (in general?)

### ISSUE THREAD

**Issue by lim0606** [Lasagne/Lasagne#283]
Hi, 

I recently started to use Lasagne. The interface of this library is really cool, but it seems to have critical issues in either memory or optimisation.  

I tested examples in `example/mnist_conv.py` and `example/mnist_conv_dnn.py`, and both example gave me nan loss. 

Actually I found this behaviour when I try to re-implement variational auto encoder with Lasagne by comparing with https://github.com/y0ast/Variational-Autoencoder.

I checked that the gradients is properly calculated, and I also checked that the program works when I convert params to cpu memory, update them in cpu, and set to gpu memory again.   
The working code is here https://github.com/lim0606/vae

In that sense, the error come from gpu memory? or updating mechanism?

I'm using Titan Z (346.59), CUDA 6.5, cuDNN R2, Theano 0.7, and the most recent commit of Lasagne.

**Comment by benanne** [comment]
Those examples work just fine here, so there may be an issue with your Theano, CUDA or cuDNN setup, or possibly even with the hardware. Are you able to reproduce this problem with regular Theano code? I have a feeling Lasagne is not at fault here, but I could be wrong :)

Also, looking at your example code, you should make sure to use the new `lasagne.layers.get_output()` function instead of the deprecated `get_output()` method of the layer classes - especially because you are using non-deterministic layers. Have a look at this part of the docs for more info on why this is important (last 3 paragraphs especially): http://lasagne.readthedocs.org/en/latest/user/layers.html#propagating-data-through-layers

**Comment by lim0606** [comment]
Thank you for kind response!

I think you are right :) 

I checked all the setting by running test codes of essential libraries before I started to use Lasagne, but the theano.test() now gives cuda related errors, such as `FAIL: test_specify_shape_partial (theano.sandbox.cuda.tests.test_basic_ops.test_shared_options)`.

If there is still problems after fixing this, I will post further. Thank you again :)

Best regards, 

Jaehyun Lim
