### ISSUE TITLE
recursive __call__ instead of layers.get_output

### ISSUE THREAD

**Issue by recursix** [Lasagne/Lasagne#288]
I've just started to play with lasagne, please apologize my shallow understanding of the code. 

The usage of `lasagne.layers.get_output` is kind of counter intuitive to me. It uses `get_all_layers` to navigate through the code with a queue. Wouldn't it be more compact to add the following recursive function to the `Layer` class (and overriding it in `MergeLayer`) instead?
```python
    def __call__(self,inputs, **kwargs):
        if self.input_layer is not None:
            inputs = self.input_layer(inputs, **kwargs)
        return self.get_output_for(self,inputs,**kwargs)
```
This way you could replace 
```python
lasagne.layers.get_output(output_layer, X_batch)
```
by
```python
output_layer(X_batch)
```

While it's not a big difference, It feels more theanoish to me. It also makes the code more compact and avoids the usage of `isinstance` and `hasattr`. Am I missing some (many) edge cases ?

**Comment by benanne** [comment]
That's pretty much how things used to work :) Turns out there are a whole host of problems with this approach, all of which are solved by having an iterative top-level function instead of this. Have a look at the following issues and PRs to get an idea of what lead us to make this API change: #97, #104, #182 

In summary:
This approach does not work if you have multiple output layers, or if you want the output for multiple layers in the network. You could do multiple 'calls', but then there is no guarantee that the overlapping parts of the resulting Theano expressions will be merged by Theano, so it only computes them once. Additionally, if there is any kind of nondeterminism in the network (like dropout), multiple calls would result in different randomness being used in the resulting expressions.

A recursive version instead of an iterative one also fails when the network is not a tree (with a single output layer at the root), which results in the same issue. But that's a bit harder to summarize :)

`lasagne.layers.get_output()` solves these issues by:
* being iterative instead of recursive
* allowing for multiple layers to specified in a list, e.g. `x, y, z = lasagne.layers.get_output([l1, l2, l3])`. This usage ensures that the expressions `x`, `y` and `z` are 'consistent'.

**Comment by recursix** [comment]
Makes sense, thanks for the quick answer :)
