### ISSUE TITLE
Generalize ElemwiseSumLayer

### ISSUE THREAD

**Issue by skaae** [Lasagne/Lasagne#300]
I need a multiplicative merge layer instead of sum. What are the thoughts about generalizing ElemwiseSumLayer to something like `ElemwiseMergeLayer` and let the user decide what merge function to use.

`ElemwiseMergeLayer` could be identical to `ElemwiseSumLayer` except that should take an additional merge_fun parameter. 

`merge_fun` should then be a function that takes two parameters and return the updated output. It could be inserted directly in line https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/merge.py#L94

**Comment by benanne** [comment]
If we do this it might be useful to provide `ElemwiseSumLayer` as a subclass that fixes the function to summing. But is this necessary? Do we anticipate many other merge functions being used? Not saying that it isn't, I just want to make sure we scrutinize this modification sufficiently because it adds complexity.

**Comment by skaae** [comment]
I think that multiplicative is used quite often if you have two different inputs? 
In RNN and decoder papers i have seen it in a number of places. 

Heres a suggestion: https://gist.github.com/skaae/e34d07a56920c522f6c2

merge_fun can be T.mul, T.add, T.maximum and T.minimum and maybe a few others,

**Comment by benanne** [comment]
Ah, it's pretty nice that existing Theano functions can be plugged in like that. Always a plus. Looks okay to me, but I should probably defer to @f0k on this one since he implemented the original sum version. Feel free to do a PR. I'd still like to have an `ElemwiseSumLayer` subclass as well though.

**Comment by skaae** [comment]
PR: https://github.com/Lasagne/Lasagne/pull/301
