### ISSUE TITLE
Typo in installation instructions

### ISSUE THREAD

**Issue by peterderivaz** [Lasagne/Lasagne#350]
The instructions at docs/user/installation.rst contain the instruction:

    python -c "import theano; print theano.sandbox.cuda.dnn.dnn_available() or theano.sandbox.cuda.dnn.dnn_avalailable.msg"

Should the second "avalailable" be spelt "available"?
If I run it as written I get a Python error message, while if I run it with the normal spelling it tells me that the library is not supported by my card.

(It may be worth noting at this point in the instructions that compute capability 3.0 is required - and that you can determine which cards support this by looking at the list here: https://developer.nvidia.com/cuda-gpus )

**Comment by f0k** [comment]
> Should the second "avalailable" be spelt "available"?

Oh, yes, of course. Thanks for reporting. Do you want to fix this yourself? Just use the "Edit on GitHub" link on the top right of that documentation page, it will allow you to edit the file in your browser and send us a pull request. Otherwise I'll do it myself, as you wish!

> It may be worth noting at this point in the instructions that compute capability 3.0 is required

That's something that should probably be prominently displayed on https://developer.nvidia.com/cudnn, but as it isn't we might add a sentence to the cuDNN installation instructions, yes. Something like this, as the second sentence:
```
Note that it requires a reasonably modern GPU with Compute Capability 3.0 or higher;
see [NVIDIA's list of CUDA GPUs](https://developer.nvidia.com/cuda-gpus).
```

**Comment by peterderivaz** [comment]
I've tried to submit a pull request here:

https://github.com/Lasagne/Lasagne/pull/351
