### ISSUE TITLE
Adam updates will return a float64 dtype for scalar parameter with the dytpe float32

### ISSUE THREAD

**Issue by lc82111** [Lasagne/Lasagne#363]
I don't know whether this counts as a bug,  but it really stop me from compiling training function.
I found this line result in this undesirable return:  `m_prev = theano.shared(param.get_value() * 0.)`
A minor modification worked for me `m_prev = theano.shared(param.get_value() * utils.floatX(0.))`

**Comment by f0k** [comment]
That counts as a bug! Thanks!

I'd actually prefer changing the initialization of `m_prev` and `v_prev` to the `np.zeros` scheme used in the other functions, such as here: https://github.com/Lasagne/Lasagne/blob/master/lasagne/updates.py#L182
That has the additional advantage of not only getting the data type correct, but also the broadcast pattern.

Do you want to send a PR? You can open https://github.com/Lasagne/Lasagne/blob/master/lasagne/updates.py in your browser and use the "Edit this file" button near the top if you don't feel comfortable setting up a fork and creating a branch yourself. Otherwise just let us know and we'll do it ourselves!

**Comment by lc82111** [comment]
hi f0k: 

I have created PR for this issue using your advice. hope it helps.
