### ISSUE TITLE
MaxPool2DLayer.ignore_border = False prevents cuDNN

### ISSUE THREAD

**Issue by f0k** [Lasagne/Lasagne#371]
As noted on the mailing list (https://groups.google.com/forum/#!topic/lasagne-users/t_rMTLAtpZo), using a MaxPool2DLayer with `ignore_border=False` prevents cuDNN from being used for the pooling operation. This is especially bad when the strides and pool size aren't equal, because in that case Theano will even fall back to a CPU implementation. This problem would be much less severe if `ignore_border=False` wouldn't be the default.

I'm not sure what the reasons were for making it the default... if it's just compatibility with Theano's [`max_pool_2d()`](http://deeplearning.net/software/theano/library/tensor/signal/downsample.html), I'd vote for breaking that compatibility for the benefit of users.
If it's also that it's common practice not to throw away the borders, then we might want to add a note that `ignore_border=True` may be a lot more performant.
Another way out would be to change Theano to use some combination of padding and cropping to allow cuDNN to be used for `ignore_border=False` as well.

**Comment by benanne** [comment]
I think that was indeed mainly for compatibility with Theano. But I agree that in this case it might be better to break that. A workaround with padding and cropping seems like a waste of time, that will also undo some of the speed benefits.

One issue is that changing this might subtly break some people's existing code in ways that they won't notice, if they've come to rely on this behaviour (perhaps unknowingly). Personally I always pay a lot of attention to ensure that all the feature map sizes / filter sizes in my networks are 'aligned' so that there are no borders anywhere, but a lot of people do not pay much attention to this.

**Comment by f0k** [comment]
> One issue is that changing this might subtly break some people's existing code in ways that they won't notice, if they've come to rely on this behaviour (perhaps unknowingly).

Yes... that's why we definitely can't change it after releasing it. The annoyance is that if we're really going to release Lasagne tomorrow, we can't really warn users in between.

> I think that was indeed mainly for compatibility with Theano. But I agree that in this case it might be better to break that.

Note that it would also enhance compatibility to `MaxPool2DDNNLayer`, which doesn't even have the `ignore_border` parameter, and to `MaxPool2DCCLayer`, which has the parameter default to `False` and fails if it's set to `True`.

> Personally I always pay a lot of attention to ensure that all the feature map sizes / filter sizes in my networks are 'aligned'

And personally I always used it with `ignore_border=True`. So at least us two wouldn't run into problems :)

Does anybody else want to chime in?
