### ISSUE TITLE
Segmentation fault (core dumped) on ubuntu linux 

### ISSUE THREAD

**Issue by khazamov** [Lasagne/Lasagne#400]
I have t1.micro instance running dnouri's tutorial on using convolutional ANNs (http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/) and I get the message that is not much informative to a developer 'Segmentation fault (core dumped)' while performing net2.fit(X,y) operation. Please, fix this

**Comment by ebenolson** [comment]
A segmentation fault is most likely a problem with your software installation or possibly a bug in Theano, not Lasagne or nolearn. But more information is necessary to debug this.

Some things you could try:
1. See if you can run the Lasagne mnist.py example.
2. See if you can run the Theano and Lasagne test suites.

As an aside, I'd recommend using one of the GPU instances rather than a t1.micro, or at least something with more RAM. I don't know if it can cause a segfault, but I wouldn't be surprised if you're running low on memory.

**Comment by f0k** [comment]
> Some things you could try:

3. Run with `gdb --args python yourscript.py yourarguments`, enter `r` so it runs, and enter `bt` when it segfaults to get a backtrace of where it segfaulted. (Most probably that will be some compiled Theano code, though, which is just mildly helpful. It might give a clue of where the bug is in Theano.)

**Comment by f0k** [comment]
Closing because there's still not enough information (and because it's a Theano issue, not a Lasagne one). If you haven't resolved the issue in the meantime, please feel free to post additional information on the error and we'll try to help you track it down!
