### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by Kaixhin** [Lasagne/Lasagne#411]
I've created [CPU-backend](https://hub.docker.com/r/kaixhin/lasagne/) and [CUDA-backend](https://hub.docker.com/r/kaixhin/cuda-lasagne/) (v6.5, v7.0 and v7.5) Docker images for Lasagne. I've checked the `mnist` and `recurrent` examples on both of these, so they seem to run fine. You may wish to add these to the [installation docs](https://lasagne.readthedocs.org/en/latest/user/installation.html) as an alternative (like [Torch7](https://github.com/torch/torch7/wiki/Cheatsheet#docker-images) or [neon](http://neon.nervanasys.com/docs/0.9.0/installation.html#docker-images)).

**Comment by benanne** [comment]
Sounds awesome! I am completely unfamiliar with Docker, could someone with some more knowledge about this stuff comment as well? From what I can see it would be a very useful addition.

**Comment by f0k** [comment]
I'm totally unfamiliar with this, too. Would you like to send a PR updating the installation docs to link to your images? I'd suggest to just add an additional section at the very end, titled "Docker images", with something like "Instead of manually installing Theano and Lasagne on your machine as described above, you may want to try a pre-made Docker image: [Lasagne Docker images (CPU)](https://hub.docker.com/r/kaixhin/lasagne/), [Lasagne Docker images (CUDA)](https://hub.docker.com/r/kaixhin/cuda-lasagne/)"
Feel free to add one or two sentences about Docker, of course, or a link to a good introduction.

> I've checked the `mnist` and `recurrent` examples on both of these

Bonus points if you can also run the test suite! The basic explanations are in the documentation ([install requirements-dev.txt](https://lasagne.readthedocs.org/en/latest/user/development.html#development-setup) and [run py.test](https://lasagne.readthedocs.org/en/latest/user/development.html#testing)), let us know if you need any help with that.
