### ISSUE TITLE
TransformerLayer doesn't handle edge pixels properly

### ISSUE THREAD

**Issue by rmanor** [Lasagne/Lasagne#442]
The interpolation in TransformerLayer averages two adjacent pixels to get the interpolated value, and multiplies it by a coefficient that is the distance of the new coordinate from the interpolated coordinates.

The adjacent pixels of the edge pixels are clipped to the same value, and so the coefficient can be zero (in the code it comes down to x = x0 = x1).

The solution I am using now is to scale the coordinates to [0, width - 2] and [0, height - 2] so there are always two adjacent pixels.

I read online that a common solution for edges is take only one closest pixel.

**Comment by skaae** [comment]
> The solution I am using now is to scale the coordinates to [0, width - 2] and [0, height - 2] so there are always two adjacent pixels.

Have you checked that it gives the correct output? If so feel free to create PR

**Comment by f0k** [comment]
You're talking about this part, right? https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/special.py#L275-L285
```python
    # scale indices from [-1, 1] to [0, width/height].
    x = (x + 1) / 2 * width_f
    y = (y + 1) / 2 * height_f

    # Clip indices to ensure they are not out of bounds.
    max_x = width_f - 1
    max_y = height_f - 1
    x0 = T.clip(x, 0, max_x)
    x1 = T.clip(x + 1, 0, max_x)
    y0 = T.clip(y, 0, max_y)
    y1 = T.clip(y + 1, 0, max_y)
```

To get all the code together, the problem arises in this part: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/special.py#L311-L323
```python
    # use indices to lookup pixels for all samples
    im_flat = im.reshape((-1, channels))
    Ia = im_flat[idx_a]
    Ib = im_flat[idx_b]
    Ic = im_flat[idx_c]
    Id = im_flat[idx_d]

    # calculate interpolated values
    wa = ((x1_f-x) * (y1_f-y)).dimshuffle(0, 'x')
    wb = ((x1_f-x) * (y-y0_f)).dimshuffle(0, 'x')
    wc = ((x-x0_f) * (y1_f-y)).dimshuffle(0, 'x')
    wd = ((x-x0_f) * (y-y0_f)).dimshuffle(0, 'x')
    output = T.sum([wa*Ia, wb*Ib, wc*Ic, wd*Id], axis=0)
```

If `x` is 1, then `x` will become `width_f`, then both `x0` and `x1` will be set to `width_f - 1`. In the interpolation (second code excerpt), all four weights will be zero because `x1_f - x == 0` and `x - x0_f == 0`, and then the output becomes zero as well.

What we want is to replace coordinates outside the image with an edge pixel.

I think the easiest fix would be to change the mapping in the beginning. Note that we've got the same problem for negative coordinates, they'd result in `x0 == x1 == 0` and give zero weights for the interpolation as well. The following should work:
```python
    # scale indices from [-1, 1] to [0, width/height - 1].
    x = (x + 1) / 2 * (width_f - 1)
    y = (y + 1) / 2 * (height_f - 1)

    # Clip indices to ensure they are not out of bounds.
    x0 = T.clip(x, 0, width_f - 2)
    x1 = x0 + 1
    y0 = T.clip(y, 0, height_f - 2)
    y1 = y0 + 1
```

@skaae, am I missing a reason for scaling x/y to width/height instead of (width-1)/(height-1)? And am I missing a reason for simply setting `x1 = x0+1` after correct clipping of `x0`? This should do what we want for all edges. Or did you actually want the image to be zero-padded?

@rmanor, do you want to file a PR or shall we do it? In any case, the PR should include a new test case that checks whether an input image passes through unchanged if the localization layer says [1, 0, 0, 0, 1, 0].

**Comment by rmanor** [comment]
@skaae The output looks ok to me, but I didn't do any real tests yet.

@f0k If you have the time then please go ahead and send the PR. Thanks.
Btw, I did the other way around - I scaled to [0, width/height -  2].

**Comment by skaae** [comment]
> am I missing a reason for scaling x/y to width/height instead of (width-1)/(height-1)?

are you refering to `x = (x + 1) / 2 * width_f` ? I agree that it should probably be `x = (x + 1) / 2 * (width_f-1)`

> And am I missing a reason for simply setting x1 = x0+1 after correct clipping of x0? This should do what we want for all edges. Or did you actually want the image to be zero-padded?

I probably had out of bounds errors and clipped everything to ensure that it was within the image. 
I think you are correct that clipping `x0` to `width-2` would solve the problem. Same goes for y.

Are you creating a PR or should I do it?

**Comment by f0k** [comment]
> are you refering to `x = (x + 1) / 2 * width_f`? I agree that it should probably be `x = (x + 1) / 2 * (width_f-1)`

Yes, that's what I meant. If you regard `x = 0` as the center of the leftmost pixel and `x = width-1` as the center of the rightmost pixel, that would be the correct scaling.

> Are you creating a PR or should I do it? 

I'll start one.

**Comment by f0k** [comment]
There is another problem:
```python
    # calculate interpolated values
    wa = ((x1_f-x) * (y1_f-y)).dimshuffle(0, 'x')
    wb = ((x1_f-x) * (y-y0_f)).dimshuffle(0, 'x')
    wc = ((x-x0_f) * (y1_f-y)).dimshuffle(0, 'x')
    wd = ((x-x0_f) * (y-y0_f)).dimshuffle(0, 'x')
    output = T.sum([wa*Ia, wb*Ib, wc*Ic, wd*Id], axis=0)
```
x0 and x1 are currently constrained to be inside the image with x0 <= x1, but x is not. In particular, it's possible that x < x0 or x1 < x. If that happens, you'll get negative weights for `wa`, `wb`, `wc` or `wd` (very large ones if x is far outside).

So apart from solving the original problem (a neutral transformation cuts away the right and bottom border), what do we want to happen with sample coordinates exceeding the image boundaries? Clip them to the boundaries (that's doable)? Treat them as pointing at zeros (that's difficult)?

**Comment by skaae** [comment]
Clip them to border pixels?
Den 29/09/2015 15.53 skrev "Jan Schlüter" <notifications@github.com>:
