### ISSUE TITLE
set_rng and theano RandomStreams

### ISSUE THREAD

**Issue by mehdidc** [Lasagne/Lasagne#479]
In case the global random number generator is initialized with a theano RandomStreams instance with set_rng, the initialization schemes in init.py fail because it expects get_rng() to give a  numpy random generator.

**Comment by benanne** [comment]
Yes, that is the intended behaviour. When a `Layer` needs a Theano RNG, it creates it and uses the numpy rng set with `set_rng` to seed it. You can find an example here: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/noise.py#L57

Please refer to the docs for more info: http://lasagne.readthedocs.org/en/latest/modules/random.html

**Comment by mehdidc** [comment]
Ok, Thanks!  I think I was reading an older version of the doc. Then, What if we want to use a class different than MRG_RandomStreams as a random number generator ?

**Comment by benanne** [comment]
In the case of the noise layers you could simply override the `_srng` attribute after instantiation. The safest way is to subclass, I guess.

**Comment by mehdidc** [comment]
Thanks, that would solve this case. The thing is that it will be specific to a layer, what if we want to use the same  number generator on all/several layers ? I think it is cleaner to use a sort of global set_rng for theano once than setting manually _srng for all layers, what do you think ?

**Comment by benanne** [comment]
What are some concrete use cases for sharing RNGs between layers? Our approach already covers the main use case of reproducibility, and I'm having a hard time thinking of anything else that isn't an edge case.

**Comment by mehdidc** [comment]
The use case of this is to have way to select a specific "kind" of number generator, currently (by default) only MRG_RandomStreams is used.

**Comment by benanne** [comment]
Personally I believe that constitutes an edge case :) But feel free to prove me wrong. Are there any good reasons not to use it? It is the fastest option across CPU and GPU right now, isn't it? What other RNGs would you want to use and why?

That also doesn't really need sharing of a single RNG between layers, I think. Whichever RNG you wish to use, surely you can create multiple instances of it? And furthermore nothing stops you from assigning the same RNG to the _srng attribute of multiple (noise) layers.

**Comment by f0k** [comment]
> That also doesn't really need sharing of a single RNG between layers, I think. Whichever RNG you wish to use, surely you can create multiple instances of it?

That's very important to do, actually... initially, we had a single instance shared between layer instances, and Theano gave us a memory leak: https://github.com/Theano/Theano/issues/2335

> I think it is cleaner to use a sort of global set_rng for theano once than setting manually _srng for all layers, what do you think ?

For the above reason, the most we could do would be sharing the class to instantiate between layers. So we could have `set_srng()` and `get_srng()` that just work with classes or callables rather than instances. This would certainly trap up other users, though, because it's inconsistent with `set_rng()` and `get_rng()`.

So unless there's a use case that needs it, I'd suggest you to just monkey-patch `lasagne.layers.noise` before instantiating any layers: `import lasagne.layers.noise; lasagne.layers.noise.RandomStreams = what_you_want` -- we won't guarantee that this will always be possible in future, of course, and it would need to be something that follows the same interface, but it would allow you to experiment with it.
