### ISSUE TITLE
How to construct MLP with two inputs?

### ISSUE THREAD

**Issue by jerryli1981** [Lasagne/Lasagne#488]
Hi All,
I am new to Lasagne, I am wondering how to construct MLP with two inputs.
For example,  the hidden layer accept two inputs.
```
 h_layer = sigmoid(W1*X1 + W2*X2 +b)
 logistic_regression_layer = sigmoid(W*h_layer + b)
 output = softmax(logistic_regression_layer)
```
One input is quite easy based on the tutorial, However, I am confused about two inputs. Thanks in advance

**Comment by f0k** [comment]
The structure you posted would be accomplished as:
```python
from lasagne.layers import InputLayer, DenseLayer, ElemwiseSumLayer, NonlinearityLayer
from lasagne.nonlinearities import sigmoid, softmax
leg1 = InputLayer(first_input_shape)
leg1 = DenseLayer(leg1, num_units=whatever, nonlinearity=None)
leg2 = InputLayer(second_input_shape)
leg2 = DenseLayer(leg2, num_units=whatever, nonlinearity=None, b=None)
joined = ElemwiseSumLayer([leg1, leg2])
joined = NonlinearityLayer(joined, nonlinearity=sigmoid)
joined = DenseLayer(joined, num_units=whatever_else, nonlinearity=softmax)
```
Equivalently, instead of separating the two dot products (`W1*X1` and `W2*X2`), you can combine them into one:
```
from lasagne.layers import ConcatLayer
leg1 = InputLayer(first_input_shape)
leg2 = InputLayer(second_input_shape)
joined = ConcatLayer([leg1, leg2])
joined = DenseLayer(joined, num_units=whatever, nonlinearity=sigmoid)
joined = DenseLayer(joined, num_units=whatever_else, nonlinearity=softmax)
```
By the way, your example had a softmax directly on a sigmoid, I think that's not what you wanted (so I omitted the last sigmoid).

In future, please post such questions on our mailing list: https://groups.google.com/forum/#!forum/lasagne-users
This issue tracker is meant for bug reports and feature discussions. Thank you!

**Comment by jerryli1981** [comment]
Sorry for my mistake to post it as an issue. 
Thanks for your solutions.
