### ISSUE TITLE
Inconsistency between Conv2DLayer and Conv2DDNNLayer results

### ISSUE THREAD

**Issue by Atanahel** [Lasagne/Lasagne#532]
Hi,

I was trying to use the ModelZoo of Lasagne/Recipe, and mostly got it to work. However, I notice that for the VGG16 model version if I change the convolution layers from the explicit DNN version to the "normal" ones, the results get completely wrong. For the VGG_S model however, this does not happen. 

More precisely, using https://github.com/Lasagne/Recipes/blob/master/modelzoo/vgg16.py and changing :
`from lasagne.layers.dnn import Conv2DDNNLayer as ConvLayer`
to
`from lasagne.layers import Conv2DLayer as ConvLayer`,
the prediction change completely and not for the best.

Conv2DDNNLayer
<img width="788" alt="capture d ecran 2015-12-11 a 17 09 53" src="https://cloud.githubusercontent.com/assets/7132817/11748755/2238f436-a02a-11e5-93a4-237b3f1bba4a.png">

Conv2DLayer
<img width="784" alt="capture d ecran 2015-12-11 a 17 09 14" src="https://cloud.githubusercontent.com/assets/7132817/11748754/223425dc-a02a-11e5-9634-f2622239f4c4.png">

Is it a known issue?

**Comment by f0k** [comment]
> Is it a known issue?

`Conv2DDNNLayer` defaults to `flip_filters=False`, i.e., it computes a correlation rather than a convolution. When you replace it by a `Conv2DLayer`, you need to flip the filters accordingly: `W = W[:, :, ::-1, ::-1]`. (`Conv2DLayer` will soon get a `flip_filters` option as well, following recent changes in Theano, but we will probably have to live with the discrepancy forever or break backwards compatibility. On the positive side, with the recent changes in Theano, `Conv2DDNNLayer` will not really be needed for anything and we can adapt the Model Zoo examples to get rid of this pitfall.)

**Comment by Atanahel** [comment]
oh! my bad, I see... Thanks for the quick answer. :-)
