### ISSUE TITLE
lasagne.layers: 'module' object has no attribute 'dnn'

### ISSUE THREAD

**Issue by SuperLee506** [Lasagne/Lasagne#535]
When I directly enforcing a specific implementation,"lasagne.layers.dnn.Conv2DDNNLayer" to enforce cuDNN.
Then,the error shows<AttributeError: 'module' object has no attribute 'dnn'>
I use the stable version of Lasagne V1.0,just like the follow steps:
1.pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt
2.pip install Lasagne==0.1

It confued me.

**Comment by f0k** [comment]
`lasagne.layers.dnn` is not imported by default, you need to do:
```python
import lasagne.layers.dnn
```
The reason is that it can only be imported on machines with GPU and cuDNN. If we auto-import it on machines that have cuDNN and silently not import it on machines that don't, there's no place we can throw a meaningful error message if somebody tries to use `Conv2DDNNLayer` on a machine that doesn't support it. So we require importing it explicitly. We should probably add a hint to the top of http://lasagne.readthedocs.org/en/latest/modules/layers/dnn.html to make users aware of that. I'm adding this to #524. Thanks!
