### ISSUE TITLE
Word dropout

### ISSUE THREAD

**Issue by mzhai2** [Lasagne/Lasagne#546]
Using dropout on the inputlayer for dropping out words in a sentence, say an int32 matrix doesn't work since the self._srng.binomial is called with dtype floatX. Maybe it should just use the input dtype?

**Comment by f0k** [comment]
Good call. `binomial()` gives a tensor of zeros and ones, so this can be expressed in whatever dtype the input has. Would you like to send a PR?

PS: Note that you'll also have to set `rescale=False` if you want integer output, otherwise it will divide the input tensor by the inverse dropout probability.

**Comment by mzhai2** [comment]
Sure, here are the paper suggesting the word dropout, http://papers.nips.cc/paper/5949-semi-supervised-sequence-learning.pdf http://arxiv.org/abs/1512.05287
