### ISSUE TITLE
The line 119 in Lasagne/lasagne/layers/merge.py has a bug

### ISSUE THREAD

**Issue by ciaua** [Lasagne/Lasagne#551]
Line 119:
`slices_by_input = [[] for i in range(ndim)]`

Should be:
`slices_by_input = [[] for i in range(len(inputs))]`

ndim is the dimension of the tensors.
The ndim should be replaced with len(inputs) because each element in the list is corresponding to an input.

**Comment by benanne** [comment]
Have you run into problems because of this? I don't fully understand the code, but to me it seems equally likely that the comment above it is wrong :) Either way we need to fix it. Thanks for the report!

**Comment by ciaua** [comment]
Yes, I got a DisconnectedInputError because some inputs are discarded due to this issue. 

For example, it happens when I concatenate a list of 5 inputs of tensor dimension 4. At the line 159 after doing the zip(inputs, slices_by_input), the length of the inputs is reduced to 4 while it should be 5.

After I correct line 119 in the source code, it is all good now.

**Comment by benanne** [comment]
In that case it's weird that this hasn't come up before! I guess people usually have fewer inputs than dimensions. Anyway, if you want to do a PR that would be very welcome :) If not then I'm sure someone else will take care of it soon. We'll definitely want to add a test for this case (more inputs than dimensions) as well so the bug is never reintroduced.

**Comment by skaae** [comment]
I couldn't figure out how to checkout this PR. I created a new pr that adds a test https://github.com/Lasagne/Lasagne/pull/555
