### ISSUE TITLE
Theano tensor support for compute_norms

### ISSUE THREAD

**Issue by kmyid** [Lasagne/Lasagne#573]
Hi, I think it would be nice to have tensor support for the compute_norms function.
I don't think it would be hard, as some other functions in utils.py already has that option.
Also, maybe adding support for bias (which would just return the absolute value), just for the sake of compatibility.

Thanks,
Kwang

**Comment by f0k** [comment]
> Hi, I think it would be nice to have tensor support for the compute_norms function.
I don't think it would be hard, as some other functions in utils.py already has that option.

It would just require a case distinction for a single line (that currently calls `np.sqrt(...)`).
What would be your use case?

> Also, maybe adding support for bias (which would just return the absolute value)

What would be the advantage over directly calling `T.abs(bias)`, though?

**Comment by kmyid** [comment]
> It would just require a case distinction for a single line (that currently calls np.sqrt(...)).
> What would be your use case?
Well, in my case I was monitoring the norm of the weights being learned and computing it through theano was obviously way faster than using get_value and numpy. And what you suggested is pretty much what I did, but not in a hacky way.
> What would be the advantage over directly calling T.abs(bias), though?
The advantage would be that you can use the same function for all parameters of the network, without distinction between weights and biases.

**Comment by kmyid** [comment]
Sorry for the closing and reopening :-( clickmiss.

> It would just require a case distinction for a single line (that currently calls np.sqrt(...)).
> What would be your use case?

Well, in my case I was monitoring the norm of the weights being learned and computing it through theano was obviously way faster than using get_value and numpy. And what you suggested is pretty much what I did, but not in a hacky way.

> What would be the advantage over directly calling T.abs(bias), though?

The advantage would be that you can use the same function for all parameters of the network, without distinction between weights and biases.

**Comment by f0k** [comment]
> Sorry for the closing and reopening

Happens to the best. When you're thinking about closing the tab and then see a "Close" button, it takes a lot of focus to resist :)

> Well, in my case I was monitoring the norm of the weights being learned

But then don't you monitor the total norm of the weights instead of the norm per unit? For this, you can just use `lasagne.regularization.l2()` (both for weights and biases).

> The advantage would be that you can use the same function for all parameters of the network, without distinction between weights and biases.

Thinking about it, returning `T.abs()` for a vector would be consistent in that it would compute the norm per unit (neuron, feature map, ...). So this seems to be the right way to do it.

I'm fine with both your suggestions. Do you want to go ahead and implement them, along with tests? We can guide you through it if you need help. For starters, [the contribution guide](http://lasagne.readthedocs.org/en/latest/user/development.html#how-to-contribute) tells you how to set up Lasagne for development.

**Comment by kmyid** [comment]
> But then don't you monitor the total norm of the weights instead of the norm per unit? For this, you can just use lasagne.regularization.l2() (both for weights and biases).

Correction: I was indeed actually monitoring per-unit.

> I'm fine with both your suggestions. Do you want to go ahead and implement them, along with tests? We can guide you through it if you need help. For starters, the contribution guide tells you how to set up Lasagne for development.

Sure, I will go ahead and implement them. And will also make sure to look carefully in the contribution guide first :-)

**Comment by f0k** [comment]
:+1:!
