### ISSUE TITLE
Box-constraints on parameters

### ISSUE THREAD

**Issue by wielandbrendel** [Lasagne/Lasagne#640]
In principle element-wise box-constraints (at least of the type x \in [-b, b]) can be added through norm_constraint() on the updates, but is there a way to directly define those constraints in the layer itself (so without the need for manual intervention during the computation of the updates)?

**Comment by benanne** [comment]
You could replace a given parameter variable `W` with `theano.tensor.clip(W, -b, b)`, that should have the desired effect.

**Comment by wielandbrendel** [comment]
Unfortunately that is not the same: directly clipping in the graph will remove gradient updates for any value that is beyond the clipped range. In other words, it makes a difference to simply use clip in the graph compared to clipping the parameters during the update. Here is a simply toy example:

https://gist.github.com/anonymous/a7ec93eb85f470840200

**Comment by benanne** [comment]
But if I understood correctly, clipping the gradient does not implement a box-constraint. Clipping the gradients will not constrain the parameters to any range. I think "clip in graph" is the correct way to do this. Unless a box-constraint is not what you actually want, of course :)

If gradient clipping is what you want, I don't think there is currently a way to do this within the layer code (because the gradient is obtained only after calling `T.grad` outside of the layer context).

**Comment by benanne** [comment]
If you clip in the graph you would of course have to substitute T.clip(W, 0, 1) everywhere you used W previously. I think both ways are valid implementations of box-constraints, but they may indeed lead to different results. If you want the "update clipping" strategy, I don't think that's currently possible at the `Layer` level, because `T.grad` is never called in that context (so you can't override the gradients). There may be some obscure Theano trick to achieve this though :)

**Comment by wielandbrendel** [comment]
> If you clip in the graph you would of course have to substitute T.clip(W, 0, 1) everywhere you used W previously.

Sure :). But you'd still end up with "dead" parameters that are never going to be updated throughout their entire lifetime (see my little toy example).

You are probably right that there is no way to implement this on the level of the layer, but one could implement this through the update function (which could "check" for each parameter whether there is a constraint defined, and to clip accordingly). Or one could add a key 'clip=(0,1)' to add_param, and to then define an update function (similar to apply_momentum) that adds those constraints. Thinking about this, this is probably what I will do for now. For core lasagne this looks to add too much clutter for too specific use cases, so maybe one could have that as a recipe.

**Comment by f0k** [comment]
> For core lasagne this looks to add too much clutter for too specific use cases

Agreed! This doesn't warrant changing the API (there'd probably be lots of other things we could add in this way, but it would clutter the API). To not change Lasagne at all, you could have a list of layers you want to clip the weight values for and then just do something like (after creating your updates dictionary):
```python
for w in itertools.chain.from_iterable(layer.get_params(regularizable=True)
                                       for layer in clipped_layers):
    updates[w] = T.clip(updates[w], 0, 1)
```
