### ISSUE TITLE
How  can I set the different learning rate of each layer in the network?

### ISSUE THREAD

**Issue by 1461190388** [Lasagne/Lasagne#648]

**Comment by benanne** [comment]
Instead of using `get_all_params()` to obtain the parameters of the model, you could use `get_all_layers()`, iterate through them and construct an updates dictionary for each layer separately. Then you just merge those together.

For questions like this one, you should use the [mailing list](https://groups.google.com/forum/#!forum/lasagne-users) instead, as indicated in our [contribution guidelines](https://github.com/Lasagne/Lasagne/blob/master/CONTRIBUTING.md) which are linked at the top of the issue submission form.
