### ISSUE TITLE
autoencoder sizes don't match

### ISSUE THREAD

**Issue by ranigb** [Lasagne/Lasagne#668]
I am trying to train an autoencoder but without connecting the weights of the conv layer with the weights of the deconv layer. This is why I was so happy with the recent addition of the transposed layer (thanks!!!). 

Unfortunately, I can't get it to work as expected (might be my fault). Here is how I create the network:

```
from lasagne.layers import InputLayer, DenseLayer, ReshapeLayer, Upscale2DLayer, Conv2DLayer, MaxPool2DLayer, NonlinearityLayer, BiasLayer, TransposedConv2DLayer
import lasagne

class Network(object):
    def __init__(self, input_dim1, input_dim2, input_dim3):
        l_inp = InputLayer((None, input_dim1, input_dim2, input_dim3))
        l_conv1 = Conv2DLayer(l_inp, 16, 11, 3, 0, W=init.Normal(0.01),nonlinearity=lasagne.nonlinearities.sigmoid)
        l_deconv1 = TransposedConv2DLayer(l_conv1, l_conv1.input_shape[1], l_conv1.filter_size, stride = l_conv1.stride, crop = l_conv1.pad, W=init.Normal(0.01),nonlinearity=lasagne.nonlinearities.sigmoid)
        out = ReshapeLayer(l_deconv1, ([0], -1))
        self.head = out

```

I try to apply it to images of size 3x250x250 but the transposed layer ends up being of size 3x248x248. Here are the sizes of the different layers:
```
<class 'lasagne.layers.input.InputLayer'> (None, 3L, 250L, 250L)
<class 'lasagne.layers.conv.Conv2DLayer'> (None, 16, 80L, 80L)
<class 'lasagne.layers.conv.TransposedConv2DLayer'> (None, 3L, 248L, 248L)
<class 'lasagne.layers.shape.ReshapeLayer'> (None, 184512)

```
What am I doing wrong?

**Comment by f0k** [comment]
This needs an additional `output_size` constructor argument for the `TransposedConv2DLayer`, I didn't have the time to include that one in the first PR. It will always reconstruct the minimum possible size that would have resulted in the given feature map size in the forward pass. If you apply it to images of 248x248, you will get back images of 248x248 fine. Otherwise you'll need to hack your TransposedConv2DLayer such that `get_output_shape_for()` returns the output size you want (this is used in `get_output_for()` as well).

**Comment by ranigb** [comment]
Thank you so much
