### ISSUE TITLE
Have Lasagne supported Multi-GPU ?

### ISSUE THREAD

**Issue by rongrongxiangxin** [Lasagne/Lasagne#676]
as the title said

**Comment by f0k** [comment]
Since Lasagne uses Theano in a very transparent way, all means of using multiple GPUs in Theano are also possible in Lasagne.
For model parallelism, you may want to try Theano's new backend: http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html
For data parallelism, you could try platoon: https://github.com/mila-udem/platoon/
There is no multi-GPU example for Lasagne yet, but if you create one, you're welcome to submit it to [Lasagne/Recipes](//Lasagne/Recipes).

In future, please post such questions on our mailing list as indicated in the yellow link above the issue submission form. The issue tracker is meant for bug reports and feature discussions only. Thank you!

**Comment by justheuristic** [comment]
Here's one way you could do multi-gpus with contexts: https://github.com/Theano/Theano/issues/6122
