### ISSUE TITLE
Leaky Rectifier activation upcasts to float64

### ISSUE THREAD

**Issue by hmendozap** [Lasagne/Lasagne#677]
Hi,

I noticed that the leaky rectifier activation upcasts the gradient of the weights in the layer. 
```
UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
  return theano.tensor.nnet.relu(x, self.leakiness)
```
I think that is related to #402 and that was closed on #661. So I just added this to the call:
```return theano.tensor.nnet.relu(x, theano.tensor.constant(self.leakiness))```

Should that be enough? Or should I also report it to Theano repo?

Thanks,
HM

**Comment by f0k** [comment]
Good catch! You should file a PR to Theano, but it should be `theano.tensor.as_tensor_variable` since `self.leakiness` (or `alpha` in the Theano function) could be a symbolic variable as well.

**Comment by hmendozap** [comment]
Thanks! Just file it.

What I found weird is that there is no upcast if alpha is a normal python float, only when is np.float32. Should lasagne avoid then float32? I'm genuinely confused with the different cases for upcasting.

**Comment by f0k** [comment]
> What I found weird is that there is no upcast if alpha is a normal python float, only when is np.float32.

Yes, that's because numpy and Theano have different upcasting rules when dealing with Python floats or Python ints. Note that the leaky rectifier formula (similar to the dropout layer and the update rules) include constants that the code originally had as Python floats or ints. Now we run into the following discrepancy:
* Python float + Python float: Python float
* Python float + numpy float32: float64
* Python float + Theano float32: float32

> I'm genuinely confused with the different cases for upcasting.

They're somewhat unexpected, that's why we didn't see the problems in the first place! They only creep up if you supply a numpy array for the dropout rate (or leakiness, or beta), not if you use a Python float or a Theano variable.

**Comment by f0k** [comment]
Fixed upstream. Thanks for the report!
