### ISSUE TITLE
There are anomalous dimensions for SPPLayer

### ISSUE THREAD

**Issue by PGrothaus** [Lasagne/Lasagne#681]
Hi,

the spatial pyramid pooling layer has some dimensions for which the window size and stride size are inconsistent with the number of output features.
E.g.:

input_shape = (batch_size,3,11,11)
pool_dims=[1,2,4]

For pool_dim=4, we will get:

win_size=(3,3)
str_size=(2,2).

We would pool at pixels 0,2,4,6,8 which will give in total 25 features, whereas there should be only 16.
The authors of the original paper must have not run in any of these issues, but I think their recipe to pool is not quite correct, or do I miss something?

To solve this, one could do sth like:

```
            pool = pool.flatten(3)[:,:,:pool_dim*pool_dim]
            pool_list.append(pool)
```

such that the number of dimensions is restricted in these cases.

**Comment by f0k** [comment]
> We would pool at pixels 0,2,4,6,8 which will give in total 25 features, whereas there should be only 16.
The authors of the original paper must have not run in any of these issues, but I think their recipe to pool is not quite correct, or do I miss something?

I kind of expected this, thanks for reporting a case where it breaks! Yes, we should figure out what's the best way to proceed in this case. Did other frameworks converge on a solution yet? I can see three options to divide 11 elements into 4 windows:
.1. Cropping the right and bottom border, as you proposed:
```
xxxxxxxxx--
www
  www
    www
      www
```
.2. Using irregular strides:
```
xxxxxxxxxxx
www
   www
     www
        www
```
.3. Padding the right and bottom border:
```
xxxxxxxxxxx0
www
   www
      www
         www
```
.4. Not allowing this case.

I currently don't have the time to think this through -- if you do, could you figure out when exactly it breaks? Would we always just have to pad a little? Do other frameworks implement spatial pyramid pooling?

**Comment by luizgh** [comment]
Hi,

I am having the same problem here. Since this is still an open issue, I started gathering more information about it. Here is what I got so far:

1) The SPP layer with default pooling regions (1,2,4) returns a different output size if either the height or width of the incoming layer is 6, 7 or 11 (I checked all input sizes ranging from 4x4 to 1000x1000, and these were the only problematic cases)
2) The problem affects the 4x4 pooling region (2x2 and 1x1 are not affected)


Looking in appendix A of the original article (https://arxiv.org/abs/1406.4729), the authors seem to have implemented this with a mix of different strides and pooling sizes. Following the inline equations in the end of page 12, the implementation for an input of size 11 would be:

```
xxxxxxxxxxx
www
  wwww
     wwww
        www
```

This seems to be arbitrary, however. The padding solution also seems reasonable to me, but it seems that it would need to consider these three cases individually:

input shape = 6
```
0xxxxxx0
ww
  ww
    ww
      ww
```

input shape = 7
```
xxxxxxx0
ww
  ww
    ww
      ww
```

input shape = 11
```
xxxxxxxxxxx0
www
   www
      www
         www
```

Any thoughts?

**Comment by luizgh** [comment]
Here is another approach to this problem: since the number of output units is small (21 in the default setting), we can implement this directly in Theano, "manually" slicing the input for each output neuron. I have implemented this and it doesn't seem to add too much computational overhead:

```
import theano.tensor as T
import theano

def pooling_fixed_output_size(inputs, output_size, pooling_op=T.max):
    """ Performs a pooling operation that results in a fixed size. Refer
        to appendix A in [1]

        Parameters
        ----------
        inputs : tensor with 4 dimensions (N x C x H x W)
        output_size: integer
        pooling_op: the pooling operation (default: MAX)

        Returns a tensor with 3 dimensions (N x C x output_size*output_size)
        
        [1] He, Kaiming et al (2015):
           Spatial Pyramid Pooling in Deep Convolutional Networks
           for Visual Recognition.
           http://arxiv.org/pdf/1406.4729.pdf.
    """
    h, w = inputs.shape[2:]

    result = []
    n = float(output_size)
    for row in range(output_size):
        for col in range(output_size):
            start_h = T.floor((row)/n*h).astype('int32')
            end_h = T.ceil((row+1)/n*h).astype('int32')
            start_w = T.floor((col)/n*w).astype('int32')
            end_w = T.ceil((col+1)/n*w).astype('int32')

            this_result = pooling_op(inputs[:,:,start_h:end_h,start_w:end_w], axis=(2,3))
            result.append(this_result.dimshuffle(0,1,'x'))
    return  T.concatenate(result, axis=2)

def SpatialPyramidPooling(inputs, pool_sizes=[4,2,1]):
    """ Spatial Pyramid Pooling 
    
    """
    result = []
    for p in pool_sizes:
        result.append(pooling_fixed_output_size(inputs, p))
    return T.concatenate(result, axis=2)
```

Note that this implementation gives the same result as the current implementation for some input sizes, but not all, so they are not interchangeable. For example, for an input size of 10, using this new implementation (as described in the appendix of paper), we already have non-uniform strides:.
```

xxxxxxxxxx
www
  www
     www
       www
```

Nevertheless, here is the code to check that this new implementation gives the same answer for a 20x20 input:

```
# Compile function to get results of this new implementation
inputs = T.tensor4()
output = SpatialPyramidPooling(inputs)
get_output_new_spp = theano.function([inputs], output)


# Compile function to get results of the current dnn.SPP implementation
import lasagne
from lasagne.layers.dnn import SpatialPyramidPoolingDNNLayer
from lasagne.layers import InputLayer

i = InputLayer((None,None,None,None))
spp_layer = SpatialPyramidPoolingDNNLayer(i)

output_dnn_spp = lasagne.layers.get_output(spp_layer)
get_output_dnn_spp = theano.function([i.input_var], output_dnn_spp)


# Check if both are equal
import numpy as np
feature_maps = np.random.random((100, 128, 20,20)).astype(np.float32)
np.allclose(get_output_new_spp(feature_maps), get_output_dnn_spp(feature_maps))
# returns True
```


I tested this on an NVIDIA P-100 GPU, and this method was between 50% and 100% slower than the current implementation, depending on the input sizes. However, this cost is often a small fraction of the forward propagation time.

```
feature_maps = np.random.random((100, 128, 4,4)).astype(np.float32)
%timeit get_output_new_spp(feature_maps)
#100 loops, best of 3: 3.31 ms per loop
%timeit get_output_dnn_spp(feature_maps)
#1000 loops, best of 3: 1.6 ms per loop

feature_maps = np.random.random((100, 128, 20,20)).astype(np.float32)
%timeit get_output_new_spp(feature_maps)
#100 loops, best of 3: 5.61 ms per loop
%timeit get_output_dnn_spp(feature_maps)
#100 loops, best of 3: 4.09 ms per loop
```


@f0k what do you think about this strategy?

**Comment by f0k** [comment]
> Since this is still an open issue, I started gathering more information about it.

Thank you, and sorry for the late reply! Haven't had a chance to look before.

> Looking in appendix A of the original article (https://arxiv.org/abs/1406.4729), the authors seem to have implemented this with a mix of different strides and pooling sizes.

I see, thank you for the pointer.

> The SPP layer with default pooling regions (1,2,4) returns a different output size if either the height or width of the incoming layer is 6, 7 or 11 (I checked all input sizes ranging from 4x4 to 1000x1000, and these were the only problematic cases)

It's easy to just generate ~all~ many problematic cases at once:
```python
inp_size = np.arange(100)
pool_dim = np.arange(50)[:,np.newaxis] + 1
win_size = (i + pool_dim - 1) // pool_dim
str_size = i // pool_dim
pad = 0
out_size = i + 2*pad - win_size + 1
wrong = out_size != pool_dim
```
Now `wrong[p,i]` says whether the output size is wrong for input size `i` and number of pooling bins `p+1`.

> The padding solution also seems reasonable to me,

It doesn't seem so easy, unfortunately. Note that there are many more broken cases for larger numbers of pooling bins, such as 6:
```
xxxxxxxxx
ww
 ww
  ww
   ww
    ww
     ww
      ww
       ww
```
For 9 inputs, the current implementation gives 8 instead of 6 output locations. We could pad this to 12 inputs and increase the stride to 2, but then one of the windows would just be two zeros. We could also crop it to 7 inputs and keep the stride at 1, but then we'd loose some data. Both is a bit unsatisfactory.

> what do you think about this strategy?

It's nice that it's still reasonably fast, and that it's following the paper. I think we shouldn't replace the default implementation with this, both for backwards compatibility and for performance reasons, but we could add a `mode` argument to the layer to control which implementation to choose. This one could be called `mode='kaiming'`.

Another aspect is that your implementation does not require cuDNN. The bleeding-edge version of Theano also doesn't require cuDNN for pooling with symbolic stride and window size. We could add `lasagne.layers.pool.SpatialPyramidPoolingLayer`, with an implementation compatible to `SpatialPyramidPoolingDNNLayer`, and a `mode` keyword for the alternative implementation. Fixing the default implementation would have to be deferred until we have a bright idea :)

**Comment by luizgh** [comment]
Indeed, that are many more problematic cases. The ones I had identified (input sizes 6,7,11) only apply for the output pool size of 4.

I think it makes sense to add a new mode (e.g. mode='kaiming') for the method, using this new implementation, as described in the paper. 

However, there is another property of this implementation that requires some thought: this operation is well defined even when the output size of the pooling operation is larger than the input size. In the previous implementation (using dnn.pool), this would raise an error. For example:

```
feature_maps = [[0,1],
                [2,3]]
feature_maps = np.array(feature_maps).reshape(1,1,2,2).astype(np.float32)
output = get_output_new_spp(feature_maps)
output[:,:,0:16].reshape((4,4))
#array([[ 0.,  0.,  1.,  1.],
#       [ 0.,  0.,  1.,  1.],
#       [ 2.,  2.,  3.,  3.],
#       [ 2.,  2.,  3.,  3.]], dtype=float32)

get_output_dnn_spp(feature_maps)
# Error
```

Should this be allowed or return an error? It doesn't seem necessarily wrong, but it is strange to have a larger output as a result of a pooling operation. 

Also, a technical question: you mentioned that the new version of Theano supports pooling with symbolic strides/window sizes. How do you handle this dependency in Lasagne? For instance, should any part of the code check if a particular version of Theano is available, or you just keep this on the "bleeding edge" version of lasagne, until this feature becomes part of the stable version Theano?


PS:  There was one line missing in the code snippet you posted (to check when the current method has an incorrect output size):

```
import numpy as np

inp_size = np.arange(100)
pool_dim = np.arange(50)[:,np.newaxis] + 1
win_size = (inp_size + pool_dim - 1) // pool_dim
str_size = inp_size // pool_dim
pad = 0
out_size = inp_size + 2*pad - win_size + 1
out_size = (out_size + str_size -1) // str_size  # <---
wrong = out_size != pool_dim
```

Now we see that the output pool size of 4,  ```wrong[3,:]```, is problematic for ```input < 4 or input in [6,7,11]```

**Comment by f0k** [comment]
> Should this be allowed or return an error?

I think this should be allowed. The idea is to have the output shape fully independent of the input shape, so you can throw anything at the network you want. It's okay if only the `kaiming` mode actually works in this case.

> How do you handle this dependency in Lasagne? For instance, should any part of the code check if a particular version of Theano is available, or you just keep this on the "bleeding edge" version of lasagne, until this feature becomes part of the stable version Theano?

In the past, we just upgraded the `requirements.txt` whenever we needed a more recent Theano feature. But my ideal plan would be to keep Lasagne 0.2 compatible with Theano 0.8.2. If we stick to this, the code should indeed check whether the feature is available and throw an error otherwise (telling to either upgrade Theano or use the `kaiming` mode).

> There was one line missing in the code snippet you posted

Oh, sorry, you're right. I just copied the lines from my prompt and missed that one.

**Comment by luizgh** [comment]
@f0k thanks for the comments.

I have implemented most of it here: https://github.com/luizgh/Lasagne/tree/SpatialPyramidPooling_kaiming

As we discussed, I added a class `lasagne.layers.pool.SpatialPyramidPoolingLayer`. This layer implements 1) The algorithm used in `dnn.SpatialPyramidPoolingDNNLayer`, but directly in theano (instead of relying on cudnn);  2) the new implementation, when the argument `mode = 'kaiming'` is informed. I have added tests (same tests used in the DNN class, plus a new test for the 'kaiming' mode). I also noticed that the `get_output_for` tests for the DNN layer only considered the "fixed" case (when the layer knows the input size beforehand) - I updated the tests to consider both cases.

On the other hand, I don't know how to implement the check for the Theano version. Using `theano.__version__` doesn't seem to be a good idea (e.g. how to support any new version while raising errors for any old version). Any suggestions on how to implement this? FYI, right now the method returns the following error for Theano version 0.8:

`ValueError: Pool downsample parameters must be ints. Got (Elemwise{int_div,no_inplace}.0, Elemwise{int_div,no_inplace}.0)`

**Comment by f0k** [comment]
> I have implemented most of it here

Nice, that was fast!

> On the other hand, I don't know how to implement the check for the Theano version. [...] Any suggestions on how to implement this?

Usually the best way is to either check for the specific functionality (using `hasattr`, on a module, for example), or just try to use the specific functionality and fall back if it doesn't. Looking at the diff of the PR that introduced variable pooling to Theano (https://github.com/Theano/Theano/pull/4756/files#diff-7e13e905a5451cdcfd78519fcca02c2fR235), a possible hook might be the `__props__` or the `__init__` keyword arguments of the `Pool` op. As long as `padding` is in there, it doesn't support variable window sizes and strides (we cannot use the window size or strides because they changed names afterwards, but we can rely on `padding` staying like this for now). So the test would be either:
```python
if 'padding' in theano.signal.pool.Pool.__props__:
    # not supported
else:
    # supported
```
or:
```python
try:
    pool_2d(T.tensor4(), ws=T.ivector(), stride=T.ivector())
except ValueError:
    # unsupported
else:
    # supported
```
I'd prefer the latter. It relies less on internals and is easier to understand.

**Comment by luizgh** [comment]
I think the latter is preferable, since we end up testing what is actually necessary (symbolic variables as input for `pool_2d`). I also think we need to check both for `ValueError` and `TypeError`, since older versions of Theano had different parameters (`ds` and `st` instead of `ws` and `stride`):

```
if mode != 'kaiming':
    # Check if the running theano version supports symbolic
    # variables as arguments for pool_2d. This is required
    # unless using mode='kaiming'
    try:
        T.signal.pool.pool_2d(T.tensor4(),
                              ws=T.ivector(),
                              stride=T.ivector(),
                              ignore_border=True)
    except (ValueError, TypeError):
        raise ImportError("SpatialPyramidPoolingLayer requires a "
                          "newer version of theano. Either update"
                          " theano, or use mode='kaiming'")
```

I am raising an "ImportError" since that's used elsewhere when the Theano version is too old. 

Let me know if this is ok, and I will submit a pool request

**Comment by f0k** [comment]
> since older versions of Theano had different parameters

That's taken care of by `pool_2d` (if you use the `pool_2d` wrapper defined in `lasagne.layers.pool`, not `T.signal.pool.pool_2d`). Note that the parameter names were changed after introducing symbolic variables, so your current check based on `T.signal.pool.pool_2d` would actually be too strict (although I doubt it would affect anyone).

**Comment by f0k** [comment]
> Let me know if this is ok,

Yes! In addition to my previous comment, the error should say `SpatialPyramidPoolingLayer with mode='fast' requires ...` (I don't know how to call the default mode, `'fast'` would tell that it's faster...)

> and I will submit a pool request

Nice pun ;)

**Comment by luizgh** [comment]
Ok, I submitted the pull request: https://github.com/Lasagne/Lasagne/pull/799

>> and I will submit a pool request

> Nice pun ;)

lol, no pun intended :). I guess I typed the word "pool" too many times in the last few days :P
