### ISSUE TITLE
CustomRecurrentLayer hid_init: Inconsistency between np.zeros(shape) and lasagne.init.constant(.0)

### ISSUE THREAD

**Issue by Quadrocube** [Lasagne/Lasagne#686]
I've recently been hacking with `CustomRecurrentLayer` and noticed a strange (at least from intuitive expectations, haven't found docs anywhere that claim otherwise) behavior: the default setting of hidden state initialization (`init.Constant(0.)`) gives dramatically different results from manual setting of `hid_init=np.zeros(hid_shape)`. When trying to emulate theano scan in a manual way (`nonlinearity=None`):

    # The layer receives (n_samples, n_ticks, n_inputs) tensor 
    # and transforms it into (n_samples, n_ticks, hidlen, hiddim), 
    # (hidlen, hiddim) being a shape of the hidden state, (20, 1) in this example
    f = theano.function([x_var], get_output(rl))
    layer_out = f(x)

    # Initialize manually-computed hidden state
    hid_state = np.zeros(hid_shape)

    # Pre-compute input-to-hidden (as per precompute_input=True)
    in_hid = lasagne.layers.get_output(rl.l_in_hid, x).eval()

    for n_tick in range(n):
        # emulate theano scan (h_t = HH(h_{t-1}) + IH(x_t))
        hid_state = lasagne.layers.get_output(rl.l_hid_hid, hid_state).eval()
        hid_state[0, :, 0] += in_hid[n_tick, :, 0]
    
        # check whether hidden state is consistent between manual and layer implementation
        assert np.allclose(layer_out[0, n_tick, :, 0], hid_state[0, :, 0], atol=1e-4), n_tick

`rl` inherits from `CustomRecurrentLayer` and is initialized as 
    
    super().__init__(incoming, self.l_in_hid, self.l_hid_hid, nonlinearity=None, learn_init=False, precompute_input=True,  hid_init=lasagne.init.constant(0.), **kwargs)

Assertion fails at `n_tick=31` for this value of `atol`. If initialized with `hid_init = np.zeros(hid_shape)` everything goes fine as expected.

I'm setting `hid_shape=(1,20,1)` during the test above. Lasagne v0.1
Being relatively new to Lasagne and Theano, having troubles in nailing it down further, but ready to provide any additional info needed.

**Comment by f0k** [comment]
> the default setting of hidden state initialization (`init.Constant(0.)`) gives dramatically different results from manual setting of `hid_init=np.zeros(hid_shape)`

This is not expected. But I'm not sure if this was because of some hack for setting the hidden state to a Theano expression that has been removed subsequently (I'm not very familiar with the recurrent layer code). Can you try [upgrading to the bleeding-edge version](http://lasagne.readthedocs.io/en/latest/user/installation.html#bleeding-edge-version) of Lasagne and Theano?

> When trying to emulate theano scan in a manual way

I'm not sure this emulation is doing the same as the real recurrent layer -- did you set `l_in_hid` to something outputting zeros?

**Comment by Quadrocube** [comment]
Updated to make it more explicit. 
Bleeding-edge version still affected. Will try to bisect minimal failure example in the meantime, will take some time due to complexity of `rl` itself.

**Comment by f0k** [comment]
`hid_shape=(1,20,1)` would be `(n_samples, hidlen, hiddim)`? Because the initial hidden state in `CustomRecurrentLayer.hid_init` should be of shape `(hidlen, hiddim)` only and replicated to match the current number of examples. Is this the culprit? If you do `hid_init=init.Constant(0.)`, what does `layer.hid_init.get_value().shape` tell?

**Comment by Quadrocube** [comment]
Yes, the first dimension stands for `n_samples` in my interpretation and it'd be logical if it was omitted in the initialization. However I get 

     RuntimeError: parameter array has shape (20, 1), should be (1, 20, 1)

from [this line](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L317) when trying to initialize with `hid_weight=np.zeros((hidlen, hiddim))`. Am I missing something here?
With `hid_init=init.Constant(0.)`, `layer.hid_init.get_value().shape` gives `(1, 20, 1)`.

**Comment by f0k** [comment]
> Am I missing something here?

Sorry, didn't know the code well enough. The `(1,)` you see is always a `(1,)`, independently of `n_samples`. It's used so the tensor already has an axis to replicate over. I don't like it, but we can't change it without breaking backwards compatibility.

Is there any other difference you can spot between initializing `hid_init` with a numpy array vs. via an Initializer object?

Otherwise, can you post a runnable example exhibiting your problem (comparing a recurrent layer with numpy array vs. `init.Constant(0.)`, not vs. a manually computed recurrency)?

**Comment by Quadrocube** [comment]
Ok, the culprit found at last. `np.zeros` gives you `float64` by default vs `float32` with `init.Constant(0.)`. And that's the reason why I wasn't able to construct a minimal failure case -- computations should get sufficiently complicated for this to take effect.
This issue can now be closed, I suppose. Thanks for helping out anyway, @f0k

**Comment by benanne** [comment]
Thanks for sharing the solution :)
