### ISSUE TITLE
[Not an issue] Proposal for metric accumulation

### ISSUE THREAD

**Issue by arogozhnikov** [Lasagne/Lasagne#687]
I've written minor class, which could be useful to lasagne users when averaging loss values / accuracies / whatever over minibatches.

Since in most cases I'm only `.append`ing something to list, I found this useful to append to lists during tuple unpacking.

I've published some [demo](http://arogozhnikov.github.io/2016/05/22/new-item-for-lists.html) how Lasagne-based code could benefit from such feature.

It would be nice to hear your suggestions or criticism.

**Comment by f0k** [comment]
I'm not sure I like the idea of adding a new class for this, but your point about the `for` loops making the MNIST example too long is worth considering!

**Comment by arogozhnikov** [comment]
Hi Jan,

> I'm not sure I like the idea of adding a new class for this

Adding a class specially for tutorial is definitely an overkill, but if such code patterns are typical for lasagne users, I think this could be something like 'a good practice'.

I'm not insisting, of course. Possibly there are better solutions.

**Comment by f0k** [comment]
> Possibly there are better solutions.

The best solution will be adding generic training loop support: #12
Unfortunately, this needs quite some thought to be generic enough (i.e., not only useful for simple cases as the MNIST example), and we haven't made this a priority.

Using a list comprehension to shorten the code is worth considering, though. The amount of code required to perform training may indeed put people off. The main reason for the explicit for loop is that it's easier to read for non-Python users.

Note that instead of your class, you can also just do:
```python
errs = [val_fn(...) for ... in ...]
val_cost, val_acc = np.mean(errs, axis=0)
```
Saves you from unzipping the list into two lists.

**Comment by arogozhnikov** [comment]
> Saves you from unzipping the list into two lists.

Nice catch, maybe I'll stick with this.
