### ISSUE TITLE
How to implementation recommend system by RNN or LSTM with Travel dataset

### ISSUE THREAD

**Issue by zero76114** [Lasagne/Lasagne#690]
I have a dataset about Travel ( ~800000 row). A small data set is below:
user_id | loc_id | num_checkin
1000003 | 168913 | 2
1000003 | 29488 | 1
1000003 | 9310 | 2
1000007 | 11138 | 1
1000007 | 11195 | 1
user_id : id of traveler;
loc_id : id of location;
num_checkin: times visit

Now, I need to implement a system to recommend location for traveler, that i want to try with Deep learning. Do you any idea about that. Please help!

**Comment by justheuristic** [comment]
Disclaimer: everything below is just my personal opinion, and i may be wrong.

Honestly, i'd reformulate this as a problem of collaborative filtering - there's just no information about the country and the user (except ID pair) in the data to squeeze any juice from deep learning.


You can find a few demos here
https://github.com/jadianes/spark-movie-lens
http://www.mickaellegal.com/blog/2014/1/30/how-to-build-a-recommender
https://github.com/anindya-saha/Machine-Learning-with-Python/blob/master/Coursera-Machine-Learning-Foundations/Recommending-Product-Song-Recommender-Tutorial.ipynb

**Comment by zero76114** [comment]
@justheuristic Thank you for your reply.
Your links are useful about Recommend system.
However, as I told that I am really new in Deep Learning, so I don't know exactly wonder if I can use Deep Learning for this situation.

**Comment by justheuristic** [comment]
<include my_previous_disclaimer.h>
Short answer: you can, but my bet it will be less efficient than vanilla recommender systems and/or require much more effort.

Long answer: 
To get something which:
* uses deep learning,
* may be better than random guessing

you may try create an embedding for country and train it in a word2vec-similar fashion:
Say, user Ui visited countries C0, C1, C2, C3, ... Cn

To create training samples, forall Ui  forall Cj
{all countries but for Cj} -> Cj
by some neural network. __maybe__   rnn that eats this sequence c by c shall work, maybe not.

__word of advice__

First train a vanilla recommender from links above, and only than think about deep learning.
This problem is certainly not the most new-to-DL-friendly.

**Comment by zero76114** [comment]
Thank you! @justheuristic 
I will try to implementation to test your bet!

Thanks again.
