### ISSUE TITLE
Support Request: Add support to theano's new backend

### ISSUE THREAD

**Issue by Sentient07** [Lasagne/Lasagne#698]
When i use the `lasagne.layers.dnn` module, it checks with theano's old backend for availability of cuDNN.
`theano.sandbox.cuda.cuda_available`
 As the old backend will be depreciated soon and developments are taking place in the new backend, i would really like to see the `lasagne.layers.dnn` module support new backend. 
For a workaround, I am currently using `lasagne.layers.Conv2DLayer` instead of `Conv2DDNNLayer` module. 
cc : @nouiz

**Comment by benanne** [comment]
Is there some sort of roadmap for Theano we can consult to determine when this is scheduled to happen, so we can prepare? The new backend has been in development for a very long time (longer than Lasagne has existed), and as far as I know the majority of Theano users are still using the old backend right now.

**Comment by f0k** [comment]
> For a workaround, I am currently using `lasagne.layers.Conv2DLayer` instead of `Conv2DDNNLayer` module.

That's recommended anyway. There is no benefit of using `Conv2DDNNLayer` since Theano's overhaul of the conv2d interface.
Is there anything else blocking you from using the new backend?

**Comment by nouiz** [comment]
We have only 1 thing to fix to have the new back-end a little faster then
the old one (~10% speed up in one case). After that, only a few not
frequent op haven't been implemented.

So I would guess we are pretty close to use it extensively here (in
particular for float16 in storage).

**Comment by f0k** [comment]
Then maybe our roadmap should be: Release Lasagne 0.2 for Theano 0.8, then switch things over to use the new backend explicitly (assuming that supporting both backends at once is a bit cumbersome).

**Comment by nouiz** [comment]
I think it should be easy to support both. If not, tell us. Mostly, from
the user point of view, it is just a few Theano flags difference.

**Comment by benanne** [comment]
Supporting both will by definition require separate code paths in some cases, won't it? (I would imagine especially for the convolutional layers.) If not then that's great, but then there wouldn't be an issue in the first place and people could just switch their flags from `device=gpu0` to `device=cuda0`. I think I agree with @f0k, we might want to do a "hard" switch and avoid littering the code with a bunch of if-statements to support both backends.

Also, if there are no use cases anymore where `Conv2DDNNLayer` offers an advantage over `Conv2DLayer`, we should probably deprecate it and encourage people to switch to the latter.

**Comment by f0k** [comment]
> Supporting both will by definition require separate code paths in some cases, won't it?

Yes. For cuDNN, the only difference is where to import the `dnn` module from. We have some other places that need adaptation, though:
```
$ grep -le sandbox */*/*.py
lasagne/layers/corrmm.py
lasagne/layers/cuda_convnet.py
lasagne/layers/dnn.py
lasagne/layers/noise.py
lasagne/layers/special.py
```
We'll need to check in detail if they also just boil down to different `import`s.

> Also, if there are no use cases anymore where `Conv2DDNNLayer` offers an advantage over `Conv2DLayer`, we should probably deprecate it and encourage people to switch to the latter.

Its only use is to enforce a specific implementation for a particular layer. This is something you can't do with Theano flags. We should try to communicate this better; people still use the DNN version because it sounds faster.

**Comment by nouiz** [comment]
corrmm isn't ported to the new back-end.

We tried to keep both interface similar. If you find case where this isn't
true, tell us.

**Comment by nouiz** [comment]
Also, normally user should be able with tag to select which convolution
implementation to use. If this isn't possible, or what is probably the case
the interface isn't interresting, tell us. We can discuss this.

**Comment by lamblin** [comment]
- lasagne/layers/corrmm.py: could be replaced by Conv2DLayer (or update the imports)
- lasagne/layers/cuda_convnet.py: is cuda-convnet still worth it these days? We have no plans to port these to the new back-end in Theano. Would it be feasible to deprecate it?
- lasagne/layers/dnn.py: could be replaced by Conv2DLayer (or update the imports)
- lasagne/layers/noise.py: do not use sandbox/cuda, just MRG_RandomStreams
- lasagne/layers/special.py: does not use sandbox/cuda, just MRG_RandomStreams

**Comment by Sentient07** [comment]
Is there a way to disable the old backend completely ? As in, when there is a call being made to the old backend, would a warning or error be displayed ? With that, I can submit a PR to get rid of the dependency of the old backend at one go.

**Comment by lamblin** [comment]
`cuda.enabled=False` in THEANO_FLAGS should disable it completely.

**Comment by borisfom** [comment]
@Sentient07 : actually, if you set config.cuda.enabled=False, it will be disabled.

**Comment by f0k** [comment]
@lamblin: Thanks for the notes! `theano.sandbox.rng_mgr` is still the way to go, right? cuda-convnet could probably be deprecated, yes. All the convolutional layer variants (corrmm, cuda-convnet, dnn) solely exist because the old conv2d interface was not expressive enough, and if they're still used today, it's mostly due to the misconception that the Conv2DDNNLayer would be faster than the Conv2DLayer.

> With that, I can submit a PR to get rid of the dependency of the old backend at one go.

At least Lasagne 0.2 should support both backends if feasible. If you can file a PR that works against both backends, that would be ideal. Otherwise it'll have to wait until 0.3. Any help with 0.2 is appreciated, my time is currently limited.

**Comment by Sentient07** [comment]
@f0k I have a quick question, in `lasagne/layers/cuda_convnet.py`, `pylearn2`'s pooling is being used. Is it to replace with the `theano/gpuarray/dnn.py:GpuDnnPool` and likewise, can I replace `FilterActs` with `GpuDnnConv` ? This probably will remove the dependency over pylearn2. 
Also, i'm having confusions regarding which pooling I should use. Should I use the `dnn.py:GpuDnnPool` or `pool.py:GpuPool`?

**Comment by f0k** [comment]
> This probably will remove the dependency over pylearn2. (from this module)

Removing the dependency on pylearn2 would defeat the purpose of this module, which is to provide the convolution and pooling implementations of cuda-convnet. This module is not imported by default, and will raise an `ImportError` exception when either cuda or pylearn2 is not available. We just need to ensure that the import correctly fails when the new gpu backend is used.

**Comment by Sentient07** [comment]
Sorry for the naive question, isn't porting the cuda code to libgpuarry's C code the purpose of newbackend? And since the newbackend is faster than the old one, why do we want to retain `cuda_convnet` (a slower implementation) ?

**Comment by f0k** [comment]
> why do we want to retain `cuda_convnet` (a slower implementation) ?

`cuda_convnet` is not necessarily slower, it's an alternative convolution implementation to the ones available directly in Theano. Probably hardly anyone uses the `Conv2DCCLayer`, but if so, it will be on purpose. We should just make `import lasagne.layers.cuda_convnet` fail if Theano is not running under the old backend or `pylearn2` is not installed. This will make it unusable under the new backend, which is totally fine (as long as the error message conveys this). Once Lasagne requires Theano 0.10, we can drop the `lasagne.layers.cuda_convnet` module completely (or replace it by a stub that only throws a meaningful `ImportError`).

**Comment by ReyhaneAskari** [comment]
@f0k , @lamblin 

I have started working on this issue. The aim is to change Lasagne such that it would be fully compatible with both the new and old backends. 

My understanding is as follows, please correct me if I'm wrong: 
When a user defines an operation like conv2d, he/she should not specify the exact device-specific implementation of that operation and Theano will handle which conv2d implementation from which backend is actually used. I don't know if there is a specific reason that Lasagne is accessing the backend directly however, I think this is not a good practice and Lasagne should not explicitly use ```theano.sandbox.cuda``` in the code. 

To fix this issue, what I have in mind is to change Lasagne's code such that it would use the normal Cpu ops. So for example, I would like to change :
```from theano.sandbox.cuda import dnn``` to ```from theano.tensor.nnet import dnn```.
And I would expect that Theano optimizations choose the right backend. 

Do you think that this is a good approach? If so, how can I test that it is using Cpu or the old backend or the new backend? Would printing the function graph give us this info? (For example seeing an op like GpuFromHost...)

**Comment by f0k** [comment]
> I don't know if there is a specific reason that Lasagne is accessing the backend directly

Yes, the reason is that `conv2d` interface did not support all possible options at the time, so we had to have extra layer types to be able to do `same` convolutions, for example.

> Lasagne should not explicitly use `theano.sandbox.cuda` in the code

I'd prefer to have the implementation-specific layers still use the specific implementation, there might be special use cases where you want a specific convolution not to be handled by cuDNN -- this is not easily possible otherwise.

> If so, how can I test that it is using Cpu or the old backend or the new backend?

That's exactly the question you'd need to find the answer to. We need a way to replace the initial checking at `lasagne.layers.corrmm` (https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/corrmm.py) with something like:
```python
if theano currently uses a gpu with gpuarray:
    from theano.gpuarray import GpuCorrMM
elif theano currently uses a gpu with sandbox.cuda:
    from theano.sandbox.cuda import GpuCorrMM
else:
    raise ImportError explaining that theano needs to be configured to use a gpu
```
It's not enough to merely check `theano.config.device`, because there are other ways to enable the GPU (we've been there before: #606). And we should not import `theano.sandbox.cuda` unless we already know that it's needed, so we need to place the gpuarray check first.

For `layers.dnn`, we additionally need to check whether DNN is available, but this should be easy once we know if and which GPU backend is in use.

For `layers.cuda_convnet`, we need to error out if the new backend is used -- this only works with the old backend.

When this is done, we will also need to update the hacks needed to build the Sphinx docs for the GPU. For more information, see:
https://github.com/Lasagne/Lasagne/pull/823#issuecomment-291807733
https://github.com/Lasagne/Lasagne/pull/823#issuecomment-291816840

It would also be helpful if you could just find out what's the equivalence of `theano.sandbox.cuda.cuda_enabled` in the new backend (i.e., a way to tell if the new backend is in use, regardless of whether it was enabled via the configuration flag or some other means). I can then probably do the rest relatively quickly.

**Comment by lamblin** [comment]
`theano.gpuarray.pygpu_activated` should be the equivalent of `cuda_enabled`.
I just checked that it is `False` by default if `device=cpu`, and is set to `True` when calling `theano.gpuarray.use(...)`.

**Comment by lamblin** [comment]
Also, we probably need to check for `import theano.sandbox.cuda` raising `ImportError`.

**Comment by ReyhaneAskari** [comment]
@f0k , @lamblin , thanks for your replies. Actually what I meant by "how to test if it's using cpu or old or new backend" was for my own testing. So for example I have made these changes but I'm not sure when I set the device to cuda, for example Conv2D is actually using the new backend. Can that be found in the profiling?

**Comment by lamblin** [comment]
The initial message "using GPU ..." should tell you which back-end is initialized at the process level.
If you want more fine-grained control, or if both are imported, then `debugprint(..., print_type=True)` should give you the data type of variables, so if the inputs/outputs of an operation are `CudaNdarrayType` it is using the old back-end, if it is `GpuArrayType`, it would be using the new.
