### ISSUE TITLE
Wrong W shape on lasagne.layers.Conv1DLayer?

### ISSUE THREAD

**Issue by julj** [Lasagne/Lasagne#747]
I am building a network to classify audio (i.e. 1D) signals.

I want two convolutional layers, one with 20 filters of 400 weights and one with 20 filters of 100 weights (with pooling in between). While the first one seems to have the right shape (20, 1, 400), the second one has shape (20, 20, 100), while I was expecting (20, 1, 100):

```
In [203]: l_in = InputLayer((50, 1, 11025)) # minibatch_len x num_features x num_time_bins

In [204]: l_conv_1 = Conv1DLayer(l_in, 20, 400)

In [205]: l_pool_1 = Pool1DLayer(l_conv_1, 4)

In [206]: l_conv_2 = Conv1DLayer(l_pool_1, 20, 100)           

In [207]: l_conv_1.get_W_shape()
Out[207]: (20, 1, 400)

In [208]: l_conv_2.get_W_shape()
Out[208]: (20, 20, 100)
```

In l_conv_1 I want 20 filters of size 400 and in l_conv_2 20 filters of size 100.

What am I missing?

**Comment by f0k** [comment]
> What am I missing?

You're missing the "channel" or "feature" dimension. Your input has a single channel (50 x **1** x 11025), so the 20 filters of your first convolutional layer have a single channel as well (20 x **1** x 400).
Because you have 20 filters, the input to the next convolutional layer has 20 features: l_conv_1.input_shape is (50, 20, something). So the 20 filters of your second convolutional layer process 20 channels each: (20 x **20** x 100).

It's the same for 2D convolution; the shape of `W` is always (num_filters, num_input_channels, all spatial filter dimensions).

In future, unless you're sure you've found a bug, please ask such questions on the mailing list instead: https://groups.google.com/forum/#!forum/lasagne-users
This helps keep the issue tracker free of usage discussions. Thank you!
