### ISSUE TITLE
A smaller network leads to more learnable parameters

### ISSUE THREAD

**Issue by ibeckermayer** [Lasagne/Lasagne#761]
I'm currently trying to get acquainted with Lasagne by running a small convolutional nn on some training data on my PC, but am running into the problem of being told I need to learn an obscene number of parameters (for my non-CUDA compatible machine), as well as an inexplicable massive **increase** in the number of parameters I'm attempting to learn when I make the network **smaller**:

Originally, I tried to train the following net: 

```python
simple_net = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', layers.Conv2DLayer),
        ('pool1', layers.MaxPool2DLayer),
        ('conv2', layers.Conv2DLayer),
        ('pool2', layers.MaxPool2DLayer),
        ('conv3', layers.Conv2DLayer),
        ('pool3', layers.MaxPool2DLayer),
        ('hidden4', layers.DenseLayer),
        ('hidden5', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 1, 288, 288),
    conv1_num_filters=32, conv1_filter_size=(3, 3), pool1_pool_size=(2, 2),
    conv2_num_filters=64, conv2_filter_size=(2, 2), pool2_pool_size=(2, 2),
    conv3_num_filters=128, conv3_filter_size=(2, 2), pool3_pool_size=(2, 2),
    hidden4_num_units=500, 
    hidden5_num_units=500,
    output_num_units=12, output_nonlinearity=None,

    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,

    regression=True,
    max_epochs=1000,
    verbose=1,
    )
```

And the console prints the following:

```
# Neural Network with 78698484 learnable parameters

## Layer information

  #  name     size
---  -------  ----------
  0  input    1x288x288
  1  conv1    32x286x286
  2  pool1    32x143x143
  3  conv2    64x142x142
  4  pool2    64x71x71
  5  conv3    128x70x70
  6  pool3    128x35x35
  7  hidden4  500
  8  hidden5  500
  9  output   12
```

This seemed excessive for a test run, so I went back to make the network smaller

```python
simple_net = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', layers.Conv2DLayer),
        ('pool1', layers.MaxPool2DLayer),
    #   ('conv2', layers.Conv2DLayer),
    #   ('pool2', layers.MaxPool2DLayer),
    #   ('conv3', layers.Conv2DLayer),
    #   ('pool3', layers.MaxPool2DLayer),
    #   ('hidden4', layers.DenseLayer),
        ('hidden5', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 1, 288, 288),
    conv1_num_filters=32, conv1_filter_size=(3, 3), pool1_pool_size=(2, 2),
    #conv2_num_filters=64, conv2_filter_size=(2, 2), pool2_pool_size=(2, 2),
    #conv3_num_filters=128, conv3_filter_size=(2, 2), pool3_pool_size=(2, 2),
    #hidden4_num_units=500, 
    hidden5_num_units=500,
    output_num_units=12, output_nonlinearity=None,

    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,

    regression=True,
    max_epochs=1000,
    verbose=1,
    )
```

and the console instead prints out 

```
# Neural Network with 327190832 learnable parameters

## Layer information

  #  name     size
---  -------  ----------
  0  input    1x288x288
  1  conv1    32x286x286
  2  pool1    32x143x143
  3  hidden5  500
  4  output   12
```

I'm using the bleeding edge version of Lasagne and Theano

**Comment by f0k** [comment]
The number of parameters of a dense layer equals to `(num_inputs + 1) * num_outputs` (`num_inputs*num_outputs` for the weight matrix, and `num_outputs` for the biases). As you can see from the first table, your first network has an input of `128x35x35` into the first dense layer, so your first dense layer has `(128*35*35 + 1)*500` parameters, that's 78,400,500. That's pretty close to the total number of parameters, since the convolutional layers have comparatively few parameters, and also the extra dense layers only have `501*500` and `501*12`, respectively. Now your attempt at making the network smaller consisted in removing some layers, so the input to the dense layer got *larger*: `32x143x143`. Consequently, the dense layer has even more parameters. To reduce the number of parameters, you need to reduce the size of the input to the first dense layer. Possibly by more pooling, or strided convolution, or global averaging. Maybe also the input of 288x288 is too detailed for a first test and you can downsample it before going into the first convolution.

Closing as it's not an issue with Lasagne. In future, please post such questions on the mailing list first, we can sort it out there and still turn it into a Lasagne issue if you found a bug. Cheers!

**Comment by ibeckermayer** [comment]
I just woke up realizing this is probably what had happened, hoping to delete the comment to save face! Oh well. Thanks, and I'll post questions like this in the mailing in the future.
