### ISSUE TITLE
receptive_field_size in the implementation of the Glorot initialization

### ISSUE THREAD

**Issue by ciaua** [Lasagne/Lasagne#772]
I am confused about the formula in the Glorot initialization:
`std = self.gain * np.sqrt(2.0 / ((n1 + n2) * receptive_field_size))`
in https://github.com/Lasagne/Lasagne/blob/master/lasagne/init.py#L103-L177

Assume we have a W with shape (num_filters, num_input_channels, filter_length_1, filter_length_2)
When we do convolution, we are doing a weighted sum with a patch with shape (num_input_channels,  filter_length_1, filter_length_2) and we get an output with shape (num_filters). 

If this is correct, isn't it that the `input size=num_input_channels*filter_length_1*filter_length_2`, the `output size=num_filters`, and the formula is `std = self.gain * np.sqrt(2.0 / (n1 + n2 * receptive_field_size))`?

Then, why there is a receptive_field_size attached to n1, too?

**Comment by f0k** [comment]
> If this is correct, isn't it that the `input size=num_input_channels*filter_length_1*filter_length_2`, the `output size=num_filters`

What you proposed is how Keras did it at first: https://github.com/fchollet/keras/blob/998efc0/keras/initializations.py#L6-L9. They then changed it to match Lasagne: https://github.com/fchollet/keras/pull/2252.
The reasoning is that the fan-out should not be the number of outputs of the forward pass (which is `num_filters`), but the number of inputs in the backward pass (which is `num_filters * filter_length_1 * filter_length_2`, since the backward pass is a convolution of the gradient wrt. the output by the same weight matrix as used for the forward pass, just with different padding and with flipped kernels).

**Comment by ciaua** [comment]
I see. Thank you.

**Comment by chinmayrane55** [comment]
Hi, thank you for your post. I had a lot of confusion for weight initialization using Glorot method. I just wanted to confirm if i am calculating fan in and fan out correctly
For above example by @ciaua  W with shape (num_filters, num_input_channels, filter_length_1, filter_length_2) the 
fan in = ( filter_length_1 * filter_length_2 * receptive field size) 
fan out = (num_filters * receptive field size) 
and just to be sure the receptive field size is number of channels in an image?

Thank in advance
