### ISSUE TITLE
Xavier / Glorot initialization docs

### ISSUE THREAD

**Issue by MartinThoma** [Lasagne/Lasagne#787]
According to the docs ([link](http://lasagne.readthedocs.io/en/latest/modules/init.html#lasagne.init.Glorot)), Glorot init is

    a = \sqrt{\frac{12}{fan_{in}+fan_{out}}}
    W \sim U[-a, a]

However, I can't find this in [the paper](http://jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf). I think it should be

    a = \sqrt{\frac{6}{fan_{in}+fan_{out}}}
    W \sim U[-a, a]

as in Equation 16 of the paper.

Also, the docs for `initializer=Normal` are a bit unfortunate. Instead of writing

    \begin{split}\sigma &= \sqrt{\frac{2}{fan_{in}+fan_{out}}}\\
    W &\sim N(0, \sigma)\end{split}

I would prefer

    \begin{split}\sigma^2 &= \frac{2}{fan_{in}+fan_{out}}\\
    W &\sim N(0, \sigma^2)\end{split}

as the second parameter of the normal distribution is commonly the variance, not the standard deviation.

**Comment by f0k** [comment]
> According to the docs (link), Glorot init is [...]

If you read closely, the example in the docs is for `gain='relu'`, hence it's a 12 in the numerator instead of a 6. I agree that this is maybe a bit confusing, trying to showcase too many things at once (the gain and the choice of distribution to draw from). I'd be fine with a PR explaining the gain in a separate sentence in the end, and possibly giving the generic formula for the standard deviation in the beginning as for `He`.

> I would prefer [...] as the second parameter of the normal distribution is commonly the variance, not the standard deviation.

True, but initialization papers often talk about the standard deviation to draw the weights from:
* https://arxiv.org/abs/1502.01852, after Eq. 10:
  > This leads to a zero-mean Gaussian distribution whose standard deviation (std) is sqrt(2/n). This is our way of initialization.
* https://arxiv.org/abs/1312.6120, end of p. 9:
  > In our context, the appropriate norm-preserving scaling for the initial condition of an N by N connectivity matrix W between any two layers corresponds to choosing each weight i.i.d. from a zero mean Gaussian with standard deviation 1 / sqrt(N).

Giving the standard deviation is also more with the API of `Normal`, `Uniform` and `Sparse`. Whether this is appropriate is another question -- but at least it's easier to implement, scaling a standard normal distribution by the standard deviation. I'd leave it as it is.
