### ISSUE TITLE
gpu memory is always increasing when using lstm from Lasagne using libgpuarray backend for Theano

### ISSUE THREAD

**Issue by xht13** [Lasagne/Lasagne#789]
i used theano-0.9.0-dev4 and cudnn 5105, cuda8.0 and gtx1080. The theano flags are "THEANO_FLAGS=mode=FAST_RUN,device=cuda0,floatX=float32".
However, when i use device=gpu0 to train the same lstm-based model (also use lstm from Lasagne), all works well and gpu memory is not increasing as training goes on.
for lstm, the input layer is" InputLayer(shape=(None, None, input_dim))", is it necessary to set the batch size and length? i run example/recurrent.py with libgpuarray, it also works well.

**Comment by nouiz** [comment]
The new Theano back-end manage gpu memory differently then the old one.

Do you end up with out of memory error or it increase for some times and
then plateau?

**Comment by xht13** [comment]
i didn't set the maximum length of input sequences, so for long sequences, it uses more memory, while for the short sequences, it uses less memory. when using old backend, it needs less memory than libgpuarray backend

**Comment by nouiz** [comment]
Theano new back-end handle memory differently then the old back-end. This
is for speed up. Can you try those 2 Theano config variable:

gpuarray.preallocate=-1
gpuarray.preallocate=0.9

The first one will disable the caching of gpu memory and is the same
default as the old back-end. You should not see more memory usage or
increase in that case. Can you confirm this?

The second will make Theano preallocate a big chunk of memory and should
speed up computation and fix the memory increase if my understanding of the
problem is good.

I think the problem you be related to fragmentation of GPU memory due to
the variable sizes.

There is another option, there is a PR that fix a memory leak in the new
back-end for the cumsum and cumprod op. Do you use them?

**Comment by yyht** [comment]
set gpuarray.preallocate=-1, i got some error for compiling. for old-backend, it doesn't have any compiling problems.
set gpuarray.preallocate=0.9 does speed up computation and fix memory increase

**Comment by f0k** [comment]
Closing this since it only relates to Theano, there's nothing we can do about it in Lasagne. Feel free to continue the discussion here and open an issue in Theano if you find something is wrong in the new backend (as opposed to an unavoidable memory fragmentation problem). @yyht, feel free to post the compilation error you get so we can have a look.
