### ISSUE TITLE
Bug in install - or bad install

### ISSUE THREAD

**Issue by dmadeka** [Lasagne/Lasagne#806]
Following the install instructions I get the following error:

``` python
/home/dhruv/anaconda2/lib/python2.7/site-packages/lasagne/utils.pyc in unique(l)
    155     new_list = []
    156     seen = set()
--> 157     for el in l:
    158         if el not in seen:
    159             new_list.append(el)

/home/dhruv/anaconda2/lib/python2.7/site-packages/lasagne/layers/helper.pyc in <genexpr>((l,))
    368     layers = get_all_layers(layer)
    369     params = chain.from_iterable(l.get_params(
--> 370             unwrap_shared=unwrap_shared, **tags) for l in layers)
    371     return utils.unique(params)
    372 

TypeError: get_params() got an unexpected keyword argument 'unwrap_shared'
```

**Comment by f0k** [comment]
> Following the install instructions I get the following error:

As far as I know, the installation instructions should not trigger such an error. What did you do *after* installing Lasagne?

Either you're mixing two Lasagne installations, or your code has a custom layer that overrides `get_param` and was for an older version of Lasagne. Can you run your code with `python -m pdb` and then do `print l` when the exception is thrown?

**Comment by dmadeka** [comment]
Im just trying to run this file:

https://github.com/SkidanovAlex/ShallowNeuralDecisionForest/blob/master/src/neuralforest.py

**Comment by dmadeka** [comment]
(and to move to Lasagne with that), but I dont see him overriding any of the layers functions, so Im not sure why there would be an error

**Comment by f0k** [comment]
> but I dont see him overriding any of the layers functions

https://github.com/SkidanovAlex/ShallowNeuralDecisionForest/blob/master/src/neuralforestlayer.py#L66

This seems to be for a very early version of Lasagne, before release 0.1. You'll need to modify the code somewhat. Since the implementation's goal seems to be not to return any parameters, you might get away with just removing the `get_params` method (and the `get_bias_params` method, but that's not used by Lasagne 0.1+ anyway).

Closing because this is not an issue with Lasagne, but feel free to post further questions in this thread or on the mailing list.
