### ISSUE TITLE
Incompatibility with numpy 1.12

### ISSUE THREAD

**Issue by rafaelvalle** [Lasagne/Lasagne#817]
When instantiating a LSTMLayer with **Numpy 1.11** this warning appears:
`
    /usr/local/lib/python2.7/site-packages/lasagne/init.py:66: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
      return floatX(get_rng().normal(self.mean, self.std, size=shape))
`

With **Numpy 1.12**, Numpy raises an error and halts the execution.

**Comment by f0k** [comment]
Does this happen with any LSTMLayer or just a specific one? Can you post a minimal runnable example producing the error (i.e., a Python script of a few lines that does the necessary imports and creates the failing LSTMLayer)? Thank you!

**Comment by rafaelvalle** [comment]
Interestingly I can't reproduce the error. Will close the issue and re-open in case it reappears!

**Comment by f0k** [comment]
In your code, the only argument requiring integers would be the shape. Maybe you created your InputLayer with float shapes, due to dividing something somewhere? We could verify or correct that in the base layer constructor; right now it accepts anything. Related: https://groups.google.com/d/msg/lasagne-users/cpVh3Nd4RJA/l2137aMsDQAJ. Pull request welcome!
