### ISSUE TITLE
AttributeError when using Conv3DLayer

### ISSUE THREAD

**Issue by vadineural** [Lasagne/Lasagne#821]
When I try to implement a 3D convolutional layer using 
`network = lasagne.layers.Conv3DLayer(network, num_filters=100,
                                          filter_size=(15, 15),
                                          stride=2,
                                          nonlinearity=lasagne.nonlinearities.rectify,
                                          W=lasagne.init.GlorotUniform())`
I get the following error:
AttributeError: 'module' object has no attribute 'Conv3DLayer'

If I replace "3D" with "2D", no error occurs.  I have the version 0.2.dev1 of lasagne and  which seems to be the newest version and Theano 0.8.0. I don't know what I am doing wrong. I am running Ubuntu 14.04. 

Thanks!

**Comment by SSSuperMac** [comment]
maybe you can try to update theano to version 0.9.0

**Comment by vadineural** [comment]
Thanks, it helped!

**Comment by f0k** [comment]
Yes, `Conv3DLayer` requires a recent version of Theano, otherwise it's disabled in Lasagne (by removing the `Conv3DLayer` definition). If you need to support older Theano versions, you can thus do:
```python
try:
    from lasagne.layers import Conv3DLayer
except ImportError:
    from lasagne.layers.dnn import Conv3DDNNLayer as Conv3DLayer
```
(Of course this requires cuDNN, which is also not necessarily available.)
Maybe we should add a note to the [Conv3DLayer docstring](http://lasagne.readthedocs.io/en/latest/modules/layers/conv.html#lasagne.layers.Conv3DLayer). Would you have read that?
(Closing because the actual issue has been resolved.)
