### ISSUE TITLE
tensor.median?

### ISSUE THREAD

**Issue by wqp89324** [Lasagne/Lasagne#827]
Is there a plan to implement tensor.median?

Thanks

**Comment by f0k** [comment]
Thanks for the suggestion, but you're in the wrong project! This should go into https://github.com/Theano/Theano/issues.
Actually there is a generic issue for implementing things missing in theano.tensor.* compared to numpy.*: https://github.com/Theano/Theano/issues/1916
And a simple workaround is to use `T.sort(x)[x.shape[0]//2]`: https://groups.google.com/forum/#!msg/theano-users/I4eHjbAetEQ/9-QFmJoaHAAJ
Closing because it concerns Theano, not Lasagne.

**Comment by wqp89324** [comment]
@f0k Thanks for your comments, I indeed should have posted on theano's page. However, I asked a question relevant to Lasagne on the mailing list, which is still about median calculation, and I used the workaround you mentioned, do you mind taking a look at the question on the mailing list titled "custom loss function that involves calculation of median"?
Thanks a lot!
