### ISSUE TITLE
how to deal with the params of CustomRecurrentlayer's input_to_hidden network(a layer)

### ISSUE THREAD

**Issue by cxy19941228** [Lasagne/Lasagne#828]
for some reason,I have to update my params in the form of orderdict.But my CustomRecurrentlayer have no direct params,all the trainable params is the params in input_to_hidden.When I update my params,first I find CustomRecurrentlayer.get_params() can not find the params hidden in input_to_hidden network,so I manually use CustomRecurrentlayer.input_to_hidden.get_params(),then the updation orderdict seems ok.But when I 'function' my whole network using theano.function([input, target,lr],[loss,error_rate,train_output],updates=updates),there is a error"unkonwn parameter type:<type'buildin_function_or_method'>".I am not familiar with theano,I used theano=0.8.2&0.9.0,they both have the same error.should I write a class that contain the input_to_hidden layer's params ?? can you gei me some advice?
many thanks

**Comment by f0k** [comment]
> CustomRecurrentlayer.get_params() can not find the params hidden in input_to_hidden network

Uhm, it should! That's precisely what the code does: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L338-L344

> can you gei me some advice?

As stated in the yellow link above the issue posting form and in the text prefilled into the issue posting form, please post on the mailing list for support questions: https://groups.google.com/forum/#!forum/lasagne-users
Let's continue the discussion there. Post an excerpt of the relevant code, you must have mistakenly included a function somewhere instead of the result of calling that function.
