### ISSUE TITLE
Training weight in vector

### ISSUE THREAD

**Issue by haozhaopop** [Lasagne/Lasagne#845]
Is it possible to train all weight and bias in one vector, instead of train one by one in a for loop?  For the moment, I want to try some optimisation algorithms which need all weights in one vector, I intend to flatten all weights, but maybe that's take a long time so that affect the result of algorithm

**Comment by f0k** [comment]
In principle, that's easy to do:

1. With `params = lasagne.layers.get_all_param_values(network, trainable=True)`, obtain all parameter values.
2. Concatenate all of them into a vector: `v = np.concatenate([p.ravel() for p in params])`.
3. Create a shared variable from that vector: `v = theano.shared(v)`.
4. Map each parameter to a slice of that shared variable:
```python
slices = {}
a = 0
for param, value in zip(lasagne.layers.get_all_param_values(network, trainable=True), params):
    b = a + value.size
    slices[param] = v[a:b].reshape(value.shape)
    a = b
```
5. Now it gets a little hairy. You need to replace all parameters referenced by the network by the slices. You can either do this with `theano.clone` on the loss expression, or try to modify the network:
```python
for layer in lasagne.layers.get_all_layers(network):
    for p in layer.params:
        if p in slices:
            layer.params[slices[p]] = layer.params.drop(p)
    for k, p in list(layer.params.__dict__.items()):
        if p in slices:
            setattr(layer, k, slices[p])
```
6. You can verify the result with something like `assert all(p.owner.inputs[0] is v for p in lasagne.layers.get_all_params(network, trainable=True))`.

Untested, but should work unless you use recurrent layers, which tuck away the parameters a bit better. In that case, you'll need a custom weight initialization class that hands out slices to a symbolic vector. (In case you don't want a shared variable for the values, but a symbolic vector that becomes an input to the Theano function, omit step 3 above, rename `v` to something else so you still have the initial vector values, and create `v = theano.tensor.vector()`. The rest will work unchanged.)

Closing because right now I'm treating this as a question, not as a feature request. A generic solution that works for all kinds of layers would be a nice addition to `lasagne.layers` or `lasagne.utils`, but not easy to do. It's easier to modify the Theano expressions.
