### ISSUE TITLE
shapes don't support numpy integral types

### ISSUE THREAD

**Issue by ssfrr** [Lasagne/Lasagne#847]
There are places where input types are being checked using `isinstance(val, int)`, which fails if `val` is a type `np.int64`. See [here](https://github.com/Lasagne/Lasagne/blob/0282a28ec84388a5756bf0f1b72d5ea02c5aa2b7/lasagne/layers/shape.py#L108-L114) for an example. It might be better here to use `isinstance(val, numbers.Integral)`, which includes the numpy integer types.

**Comment by f0k** [comment]
Sorry for the delay, I've been abroad.

> There are places where input types are being checked using isinstance(val, int), which fails if val is a type np.int64

Only in Python 3:
```bash
python3
>>> import numpy as np
>>> isinstance(np.int64(123), int)
False
```

Not in Python 2:
```bash
python2
>>> import numpy as np
>>> isinstance(np.int64(123), int)
True
```

And your proposed solution does not fix this either:
```bash
python3
>>> from numbers import Integral
>>> isinstance(123, Integral)
True
>>> import numpy as np
>>> isinstance(np.int64(123), Integral)
False
```

Do you see a different behaviour on your machine?

Your proposal would help with the `long` type in Python 2, though. When using Python 2 under Windows, ndarray shapes are `long` instead of `int`, which won't pass an `isinstance(..., int)` check. And if we want to explicitly allow numpy integers, we could use `isinstance(..., (numbers.Integral, np.integer))`.

So in general I'm all for avoiding cryptic/unfair errors. We'll need to check in detail whether this should be done by a relaxed type check or an explicit `int` conversion. Would you be willing to work on this? What was your use case / how did you find out about this?
