### ISSUE TITLE
mnist classification with trained model

### ISSUE THREAD

**Issue by ClarissaSi** [Lasagne/Lasagne#861]
I'm new in working with CNNs, Lasagne, Python,... so my question may be a bit obvious, but I don't get it: I'm trying to classify images of the mnist dataset. Therefore I used the mnist example of lasagne: https://github.com/Lasagne/Lasagne/blob/master/examples/mnist.py In line 234 I changed the model to "cnn" and uncommented the lines 336-342, so that the weights are saved in model.npz. I got an accuracy of ~99%, everything worked well. Now my question: I have the model.npz and I have an image, which I'd like to classify, but i don't get it how to do this. I read that I have to convert the .png-File to a tensor and then I can work with this. But I don't know how to do this and how to go on with the tensor. Sorry for the question if it is too obvious, but I can't find any information how I get a result, which number is in my image. 

I hope someone can help me and thanks in advance!

**Comment by f0k** [comment]
Well, first of all you need to compile a function for computing predictions:
```
pred_fn = theano.function([input_var], test_prediction)
```
This assumes everything is defined as in the example (i.e., you have built the network, loaded the weights from the model file, and defined the `test_prediction` expression).

To load the image, the first result in a major search engine is: https://stackoverflow.com/questions/31386096/importing-png-files-into-numpy
Note that it will have to match the size of the MNIST digits used for training, i.e., 24x24 grayscale, otherwise you need to convert it (e.g., with PIL, the Python Imaging Library).

Finally, compute the prediction as `pred_fn(your_image[np.newaxis, np.newaxis])` -- the `np.newaxis` will insert two dimensions in front of the height and width of your image, so it has a batch size of 1 and channel count of 1.

For the future, please post such questions on our mailing list instead (https://groups.google.com/forum/#!forum/lasagne-users), this issue tracker is meant for bug reports and feature discussions only. Thank you!
