### ISSUE TITLE
How to install Lasagne 0.2 using anaconda for 32 bit windows?

### ISSUE THREAD

**Issue by ashish2811** [Lasagne/Lasagne#872]
Is there a way to install Lasagne 0.2 using conda for 32 bit windows?

**Comment by f0k** [comment]
Possibly -- installing Lasagne is not a big deal, the main hurdle is to install Theano. For this, please refer to http://deeplearning.net/software/theano/install_windows.html, search with a search engine or ask on [theano-users](https://groups.google.com/forum/#!forum/theano-users) for this. If you get it to work, please feel free to add a guide to https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne.
Closing this issue because it's related to Theano, there is nothing we can do in Lasagne about it. Still feel free to post back here if you find out anything!
