### ISSUE TITLE
lasagne isn't running on CUDA (Windows 10) .theanorc setup

### ISSUE THREAD

**Issue by hutiwephy** [Lasagne/Lasagne#924]
kind of need help with the "Lasagne" set up it's not recognizing the .theanorc settings file and without it I can't run the "enhance" project on CUDA (I'm setting things up on Win10 but I can also do it on ArchLinux)

i was capable of compiling the "cuda_check.c" acoording to the "From Zero to Lasagne on Windows 7 (64 bit)" instructions by adding the "-allow-unsupported-compiler" flag and by being unable to install the ".NET Framework 4 sdk" I installed the "visual studio 2010 ultimate x86" which contains an amd64 VC++ compiler 

the ".theanorc" file was placed under: "[ProjectRoot]\Lasagne\WinPython\settings\\.theanorc" with the code:

```
[blas]
ldflags=-lopenblas

[gcc]
cxxflags=-I[ProjectRoot]\Lasagne\OpenBLAS\include -L[ProjectRoot]\Lasagne\OpenBLAS\lib

[global]
device=gpu
floatX=float32

[nvcc]
compiler_bindir="C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64"
flags=--cl-version=2010 -allow-unsupported-compiler
```

NOTE: it is of notice that [ProjectRoot] stands for the full path of users Desktop -> "EnhanceCLI" (project folder name)

debug-withsettings.log was made by running "python check_blas.py" from the "WinPython Command Prompt.exe"
debug-nosettings.log was made by removing ".theanorc" file from the project directory

cudacheck.log is the result of running "cuda_check.exe" compiled with current setup

[debug-nosettings.log](https://github.com/Lasagne/Lasagne/files/5233780/debug-nosettings.log)
[debug-withsettings.log](https://github.com/Lasagne/Lasagne/files/5233781/debug-withsettings.log)
[cudacheck.log](https://github.com/Lasagne/Lasagne/files/5233782/cudacheck.log)

thanks for the support!!!

____________________________________________________________________________________________________________________________________

[UPDATE]:

[ProjectRoot]\Lasagne\WinPython\settings\winpython.ini was missing "THEANORC=" variable and the 'device' variable should be equal to "cuda*" but the problem mantains and the API is still unable to run from the GPU.

[debug-newsettings.log](https://github.com/Lasagne/Lasagne/files/5234609/debug-newsettings.log)

____________________________________________________________________________________________________________________________________

**Comment by f0k** [comment]
> [ProjectRoot]\Lasagne\WinPython\settings\winpython.ini was missing "THEANORC=" variable and the 'device' variable should be equal to "cuda*" but the problem mantains and the API is still unable to run from the GPU.

Theano complains that it cannot find a C++ compiler, and that `pygpu` is not installed. For the former, you will need to make sure that a supported compiler is on your `PATH` (see [Theano installation instructions](http://deeplearning.net/software/theano/install_windows.html)). For the latter, follow the [libgpuarray installation instructions](http://deeplearning.net/software/libgpuarray/installation.html). The "From Zero to Lasagne" guide was written before libgpuarray/pygpu became the new and only supported backend, that's why it doesn't mention how to install it, and still uses `device=gpu` (old GPU backend) instead of `device=cuda` (new backend).

> (I'm setting things up on Win10 but I can also do it on ArchLinux)

Go for Linux if you have the option. The fastest way will be to install the nvidia driver, cuda toolkit, cudnn and conda, then use conda to install Theano, Lasagne, and pygpu.

**Comment by hutiwephy** [comment]
thanks
